 // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// EUROPEAN COMMISSION LIBRARY
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

if(!pst){var pst={};} // for none pst users

pst.label = {

	"en": {

		// ---------------------------------------------
		// MULTI-PAGE
		// ---------------------------------------------

		"firstPage" 	: "First page",
		"previousPage" 	: "Previous page",
		"nextPage" 		: "Next page",
		"endPage" 		: "Last page",
		"showMenuPage"	: "Choose the number of items to display",

		// ---------------------------------------------
		// DROPDOWN MENU LANGUAGE
		// ---------------------------------------------

		"wsMenuOver"	: "All available translations",
		"wsMenuLoad"	: "Please wait...",

		// ---------------------------------------------
		// WEBSERVICE
		// ---------------------------------------------

		"wsTitle"		: "All available translations",
		"wsLoading"		: "Please wait...",
		"wsSuccess"		: "Choose a language in the pop pup",
		"wsDenied"		: "Only the same domain is allowed by the webservice",
		"wsRetry"		: "No languages found",
		"wsError"		: "Webservice is busy, try later",

		// ---------------------------------------------
		// MEDIAGALLERY
		// ---------------------------------------------

		"firstMedia" 	: "First item",
		"previousMedia" : "Previous item",
		"nextMedia" 	: "Next item",
		"endMedia" 		: "Last item",
		"download"		: "Download",
		"noPlugin"		: "Format or plugin not supported.",
		"downloadPlugin": "Download the plugins",
		
		// ---------------------------------------------
		// SLIDESHOW
		// ---------------------------------------------
		
		"playMedia"		: "Play",
		"stopMedia"		: "Stop",
		
		// ---------------------------------------------
		// CALENDAR
		// ---------------------------------------------
		
		"nextMonth"		: "Next month",
		"previousMonth"	: "Previous month",
		"nextYear"		: "Next year",
		"previousYear"	: "Previous year"
		
	},
	 
  /*"en":{
    "download":"Download",
    "downloadPlugin":"Download the plug-in",
    "endMedia":"Last item",
    "endPage":"Last page",
    "firstMedia":"First item",
    "firstPage":"First page",
    "fullscreen":"Open in full screen",
    "nextMedia":"Next item",
    "nextPage":"Next page",
    "noPlugin":"Format or plug-in not supported",
    "pauseMedia":"Pause",
    "playMedia":"Play",
    "previousMedia":"Previous item",
    "previousPage":"Previous page",
    "showMenuPage":"Choose the number of items to display",
    "stopMedia":"Stop",
    "volumeMedia":"Volume",
    "wsDenied":"Only the same domain is allowed by the webservice",
    "wsError":"Webservice is busy, try later",
    "wsLoading":"Please wait…",
    "wsMenuLoad":"Please wait…",
    "wsMenuOver":"All available translations",
    "wsRetry":"No languages found",
    "wsSuccess":"Chose available languages in a pop-up",
    "wsTitle":"All available translations"
  },*/

  "bg":{
    "download":" Изтегляне",
    "downloadPlugin":"Изтеглете плъгина",
    "endMedia":" Последен",
    "endPage":" Последна страница",
    "firstMedia":" Първи",
    "firstPage":" Първа страница",
    "fullscreen":" Изображение на цял екран",
    "nextMedia":" Следващ",
    "nextPage":" Следваща страница",
    "noPlugin":"Неподдържан формат или плъгин",
    "pauseMedia":" Пауза",
    "playMedia":" Пускане",
    "previousMedia":" Предишен",
    "previousPage":" Предишна страница",
    "showMenuPage":" Избор на броя на показваните елементи",
    "stopMedia":" Спиране",
    "volumeMedia":" Сила на звука",
    "wsDenied":"Само един и същ домейн е позволен от уеб приложението.",
    "wsError":" Уеб приложението не отговаря, опитайте по-късно.",
    "wsLoading":" Моля изчакайте…",
    "wsMenuLoad":" Моля изчакайте…",
    "wsMenuOver":" Всички налични преводи",
    "wsRetry":" Не са намерени преводи на други езици",
    "wsSuccess":"Изберете език в изскачащ прозорец",
    "wsTitle":" Всички налични преводи"
  },

  "cs":{
    "download":"Stáhnout",
    "downloadPlugin":"Stáhnout zásuvný modul",
    "endMedia":"Poslední položka",
    "endPage":"Poslední strana",
    "firstMedia":"První položka ",
    "firstPage":"První strana",
    "fullscreen":"Celá obrazovka",
    "nextMedia":"Další položka",
    "nextPage":"Další strana",
    "noPlugin":"Formát a zásuvný modul nejsou podporované",
    "pauseMedia":"Pozastavit",
    "playMedia":"Přehrát",
    "previousMedia":"Předchozí položka",
    "previousPage":"Předchozí strana",
    "showMenuPage":"Zvolte počet položek k zobrazení",
    "stopMedia":"Zastavit",
    "volumeMedia":"Hlasitost",
    "wsDenied":"Webová služba povoluje pouze tutéž doménu",
    "wsError":"Webová služba je vytížená, zkuste to znovu později",
    "wsLoading":"Prosím čekejte…",
    "wsMenuLoad":"Prosím čekejte…",
    "wsMenuOver":"Všechny jazykové verze",
    "wsRetry":"Nebyly nalezeny žádné jiné jazykové verze",
    "wsSuccess":"Zvolte jazykovou verzi v nabídce pop-up",
    "wsTitle":"Všechny jazykové verze"
  },

  "da":{
    "download":"Download",
    "downloadPlugin":"Download plug-in",
    "endMedia":"Sidste element",
    "endPage":"Sidste side",
    "firstMedia":"Første element",
    "firstPage":"Første side",
    "fullscreen":"Vis i fuld skærm",
    "nextMedia":"Næste element",
    "nextPage":"Næste side",
    "noPlugin":"Format eller plug-in understøttes ikke",
    "pauseMedia":"Pause",
    "playMedia":"Spil",
    "previousMedia":"Foregående element",
    "previousPage":"Foregående side",
    "showMenuPage":"Vælg, hvor mange elementer der skal vises",
    "stopMedia":"Stop",
    "volumeMedia":"Lydstyrke",
    "wsDenied":"Webtjenesten fungerer kun inden for det samme domæne",
    "wsError":"Webtjenesten er optaget, prøv igen senere",
    "wsLoading":"Vent venligst…",
    "wsMenuLoad":"Vent venligst…",
    "wsMenuOver":"Alle tilgængelige sprogversioner",
    "wsRetry":"Ingen sprog fundet",
    "wsSuccess":"Vælg sprog i popup-menu",
    "wsTitle":"Alle tilgængelige sprogversioner"
  },

  "de":{
    "download":" Herunterladen",
    "downloadPlugin":"Zusatzmodul herunterladen",
    "endMedia":" Letztes Element",
    "endPage":" Letzte Seite",
    "firstMedia":" Erstes Element",
    "firstPage":" Erste Seite",
    "fullscreen":" Vollbildschirmanzeige",
    "nextMedia":" Nächstes Element",
    "nextPage":" Nächste Seite",
    "noPlugin":"Format oder Zusatzmodul wird nicht unterstützt",
    "pauseMedia":" Pause",
    "playMedia":" Abspielen",
    "previousMedia":" Vorheriges Element",
    "previousPage":" Vorherige Seite",
    "showMenuPage":" Anzuzeigende Elemente auswählen",
    "stopMedia":" Stop",
    "volumeMedia":" Lautstärke",
    "wsDenied":"Webservice akzeptiert nur ein und dieselbe Domäne",
    "wsError":"Webservice besetzt, später nochmals versuchen ",
    "wsLoading":" Bitte warten…",
    "wsMenuLoad":" Bitte warten…",
    "wsMenuOver":" Alle verfügbaren Sprachversionen",
    "wsRetry":" Keine Sprache gefunden",
    "wsSuccess":"Verfügbare Sprachfassungen in einem Dialogfenster auswählen",
    "wsTitle":" Alle verfügbaren Sprachversionen"
  },

  "el":{
    "download":" Τηλεφορτώστε",
    "downloadPlugin":"Τηλεφορτώστε το plug-in",
    "endMedia":" Τελευταίο στοιχείο",
    "endPage":" Τελευταία σελίδα",
    "firstMedia":" Πρώτο στοιχείο",
    "firstPage":" Πρώτη σελίδα",
    "fullscreen":" Άνοιγμα σε πλήρη οθόνη",
    "nextMedia":" Επόμενο στοιχείο",
    "nextPage":" Επόμενη σελίδα",
    "noPlugin":"Δεν υποστηρίζεται αυτό το μορφότυπο ή plug-in",
    "pauseMedia":" Παύση",
    "playMedia":" Έναρξη",
    "previousMedia":" Προηγούμενο στοιχείο",
    "previousPage":" Προηγούμενη σελίδα",
    "showMenuPage":" Επιλέξτε τον αριθμό των στοιχείων που θα εμφανιστούν",
    "stopMedia":" Διακοπή",
    "volumeMedia":"Ένταση ήχου",
    "wsDenied":"Η δικτυακή υπηρεσία επιτρέπει την πρόσβαση μόνον για τον ίδιο τομέα",
    "wsError":" Η δικτυακή πρόσβαση δεν είναι εφικτή, δοκιμάστε αργότερα",
    "wsLoading":" Περιμένετε…",
    "wsMenuLoad":" Περιμένετε…",
    "wsMenuOver":" Όλες οι διαθέσιμες μεταφράσεις",
    "wsRetry":" Δεν βρέθηκε καμία γλώσσα",
    "wsSuccess":"Επιλέξτε τις διαθέσιμες γλώσσες σε αναδυόμενο παράθυρο",
    "wsTitle":" Όλες οι διαθέσιμες μεταφράσεις"
  },

  "es":{
    "download":"Descargar",
    "downloadPlugin":"Descargar el complemento",
    "endMedia":"Último",
    "endPage":"Última",
    "firstMedia":"Primero",
    "firstPage":"Primera",
    "fullscreen":"Pantalla completa",
    "nextMedia":"Siguiente",
    "nextPage":"Siguiente",
    "noPlugin":"Formato o complemento no compatible",
    "pauseMedia":"Pausar",
    "playMedia":"Reproducir",
    "previousMedia":"Anterior",
    "previousPage":"Anterior",
    "showMenuPage":"Elija el número de elementos en la lista",
    "stopMedia":"Parar",
    "volumeMedia":"Volumen",
    "wsDenied":"El servicio web solo admite el mismo dominio",
    "wsError":"Servicio web ocupado, inténtelo más tarde",
    "wsLoading":"Espere ...",
    "wsMenuLoad":"Espere ...",
    "wsMenuOver":"Todas las traducciones disponibles",
    "wsRetry":"No se ha encontrado ningún idioma",
    "wsSuccess":"Selección de idiomas en un menú desplegable",
    "wsTitle":"Todas las traducciones disponibles"
  },

  "et":{
    "download":"Laadige alla",
    "downloadPlugin":"Laadige plugin alla",
    "endMedia":"Viimane kirje",
    "endPage":"Viimane leht",
    "firstMedia":"Esimene kirje",
    "firstPage":"Esimene leht",
    "fullscreen":"Ava täiskuva",
    "nextMedia":"Järgmine kirje",
    "nextPage":"Järgmine leht",
    "noPlugin":"Mittetoetatav vorming või plugin",
    "pauseMedia":"Paus",
    "playMedia":"Mängi",
    "previousMedia":"Eelmine kirje",
    "previousPage":"Eelmine leht",
    "showMenuPage":"Valige kuvatavate kirjete arv",
    "stopMedia":"Stop",
    "volumeMedia":"Helitugevus",
    "wsDenied":"Veebiteenus töötab üksnes samas domeenis",
    "wsError":"Veebiteenus on hõivatud, proovige hiljem uuesti",
    "wsLoading":"Palun oodake…",
    "wsMenuLoad":"Palun oodake…",
    "wsMenuOver":"Kõik saadavalolevad tõlked",
    "wsRetry":"Muid keeli ei leitud",
    "wsSuccess":"Valige olemasolevate keelte hulgast sobiv",
    "wsTitle":"Kõik saadavalolevad tõlked"
  },

  "fi":{
    "download":"Lataa",
    "downloadPlugin":"Lataa lisäohjelma (plug-in)",
    "endMedia":"Viimeinen tietue",
    "endPage":"Viimeinen sivu",
    "firstMedia":"Ensimmäinen tietue",
    "firstPage":"Ensimmäinen sivu",
    "fullscreen":"Avaa koko ruutuun",
    "nextMedia":"Seuraava tietue",
    "nextPage":"Seuraava sivu",
    "noPlugin":"Ei formaatti- tai lisäohjelmatukea",
    "pauseMedia":"Tauko",
    "playMedia":"Käynnistä",
    "previousMedia":"Edellinen tietue",
    "previousPage":"Edellinen sivu",
    "showMenuPage":"Valitse näytettävien tietueiden lukumäärä",
    "stopMedia":"Pysäytä",
    "volumeMedia":"Äänenvoimakkuus",
    "wsDenied":"Verkkopalvelu vaatii saman verkkotunnuksen",
    "wsError":"Verkkopalvelu ei ole tällä hetkellä käytettävissä, yritä myöhemmin uudelleen",
    "wsLoading":"Odota…",
    "wsMenuLoad":"Odota…",
    "wsMenuOver":"Saatavilla olevat käännökset",
    "wsRetry":"Muita kieliä ei löytynyt",
    "wsSuccess":"Valitse kieli ponnahdusvalikosta",
    "wsTitle":"Saatavilla olevat käännökset"
  },

  "fr":{
    "download":"Télécharger",
    "downloadPlugin":"Télécharger le plug-in",
    "endMedia":"Dernier élément",
    "endPage":"Dernière page",
    "firstMedia":"Premier élément",
    "firstPage":"Première page",
    "fullscreen":"Affichage en mode plein écran",
    "nextMedia":"Élément suivant",
    "nextPage":"Page suivante",
    "noPlugin":"Format ou plug-in non prévu",
    "pauseMedia":"Pause",
    "playMedia":"Lecture",
    "previousMedia":"Élément précédent",
    "previousPage":"Page précédente",
    "showMenuPage":"Choisir le nombre d'éléments à afficher",
    "stopMedia":"Arrêt",
    "volumeMedia":"Volume",
    "wsDenied":"Ce service web n'accepte que les requêtes provenant du même domaine",
    "wsError":"Ce service web est occupé. Veuillez réessayer plus tard.",
    "wsLoading":"Veuillez patienter…",
    "wsMenuLoad":"Veuillez patienter…",
    "wsMenuOver":"Toutes les traductions disponibles",
    "wsRetry":"Aucune autre langue trouvée",
    "wsSuccess":"Choisir les langues disponibles dans une liste contextuelle",
    "wsTitle":"Toutes les traductions disponibles"
  },

  "ga":{
    "download":" Íoslódáil ",
    "downloadPlugin":"Íoslódáil an breiseán",
    "endMedia":" Mír dheiridh ",
    "endPage":" Leathanach deiridh ",
    "firstMedia":" An chéad mhír",
    "firstPage":" An chéad leathanach ",
    "fullscreen":" Oscail i lánscáileán ",
    "nextMedia":" An chéad mhír eile ",
    "nextPage":" An chéad leathanach eile ",
    "noPlugin":"Níl taca le formáid nó le breiseán ",
    "pauseMedia":" Sos ",
    "playMedia":" Seinn ",
    "previousMedia":" Mír roimpi sin ",
    "previousPage":" Leathanach roimhe sin",
    "showMenuPage":" Roghnaigh líon na míreanna le taispeáint ",
    "stopMedia":" Stop ",
    "volumeMedia":" Airde ",
    "wsDenied":" Ní cheadaíonn an tseirbhís ghréasáin ach an fearann céanna ",
    "wsError":" Tá an suíomh gréasáin gnóthach, bain triail as níos déanaí ",
    "wsLoading":" Fan, le do thoil … ",
    "wsMenuLoad":" Fan, le do thoil … ",
    "wsMenuOver":" Gach aistriú atá ar fáil ",
    "wsRetry":" Ní bhfuarthas aon teanga ",
    "wsSuccess":"Roghnaigh teangacha i mír aníos ",
    "wsTitle":" Gach aistriú atá ar fáil "
  },

  "hu":{
    "download":"Letöltés",
    "downloadPlugin":"A beépülő modul letöltése",
    "endMedia":"Utolsó",
    "endPage":"Utolsó oldal",
    "firstMedia":"Első",
    "firstPage":"Első oldal",
    "fullscreen":"Megjelenítés teljes képernyőn",
    "nextMedia":"Következő",
    "nextPage":"Következő oldal",
    "noPlugin":"A formátum vagy a beépülő modul nem megfelelő",
    "pauseMedia":"Szünet",
    "playMedia":"Lejátszás",
    "previousMedia":"Előző",
    "previousPage":"Előző oldal",
    "showMenuPage":"Válassza ki a megjelenítendő elemek számát!",
    "stopMedia":"Leállás",
    "volumeMedia":"Hangerő",
    "wsDenied":"A webszolgáltatás kizárólag ugyanazon tartománynévről (domainnévről) érhető el.",
    "wsError":"A webszolgáltatás foglalt, kérjük, próbálja később!",
    "wsLoading":"Kérjük várjon…",
    "wsMenuLoad":"Kérjük várjon…",
    "wsMenuOver":"Valamennyi rendelkezésre álló fordítás",
    "wsRetry":"Nincs találat",
    "wsSuccess":"Válasszon nyelvet a felugró ablakban!",
    "wsTitle":"Valamennyi rendelkezésre álló fordítás"
  },

  "it":{
    "download":"Scarica",
    "downloadPlugin":"Scarica il plug-in",
    "endMedia":"Ultimo elemento",
    "endPage":"Ultima pagina",
    "firstMedia":"Primo elemento",
    "firstPage":"Prima pagina",
    "fullscreen":"Apri a tutto schermo",
    "nextMedia":"Elemento successivo",
    "nextPage":"Pagina successiva",
    "noPlugin":"Formato o plug-in non supportato",
    "pauseMedia":"Pausa",
    "playMedia":"Play",
    "previousMedia":"Elemento precedente",
    "previousPage":"Pagina precedente",
    "showMenuPage":"Scegli il numero di elementi da visualizzare",
    "stopMedia":"Stop",
    "volumeMedia":"Volume",
    "wsDenied":"Il servizio web consente di accedere soltanto allo stesso dominio",
    "wsError":"Servizio web occupato, prova più tardi",
    "wsLoading":"Attendere prego …",
    "wsMenuLoad":"Attendere prego …",
    "wsMenuOver":"Tutte le traduzioni disponibili",
    "wsRetry":"Nessuna lingua trovata",
    "wsSuccess":"Scegli tra le lingue disponibili nel menu a tendina",
    "wsTitle":"Tutte le traduzioni disponibili"
  },

  "lt":{
    "download":" Parsisiųsdinti",
    "downloadPlugin":"Parsisiųsdinti priedą",
    "endMedia":" Paskutinis elementas",
    "endPage":" Paskutinis puslapis",
    "firstMedia":" Pirmasis elementas",
    "firstPage":" Pirmasis puslapis",
    "fullscreen":" Rodyti visame ekrane",
    "nextMedia":" Tolesnis elementas",
    "nextPage":" Kitas puslapis",
    "noPlugin":"Formatas arba priedas nepalaikomas ",
    "pauseMedia":" Pauzė",
    "playMedia":" Leisti",
    "previousMedia":" Ankstesnis elementas",
    "previousPage":" Ankstesnis puslapis",
    "showMenuPage":" Pasirinkite rodytinų elementų skaičių",
    "stopMedia":" Stabdyti",
    "volumeMedia":" Garsas",
    "wsDenied":" Tinklo tarnyba suteikia prieigą tik prie vieno domeno",
    "wsError":" Tinklo tarnyba užimta, bandykite vėliau",
    "wsLoading":" Prašome palaukti…",
    "wsMenuLoad":" Prašome palaukti…",
    "wsMenuOver":" Visi vertimai",
    "wsRetry":" Kalbų nerasta",
    "wsSuccess":"Pasirinkti kalbą laikinajame meniu",
    "wsTitle":" Visi vertimai"
  },

  "lv":{
    "download":" Lejupielādēt",
    "downloadPlugin":"Lejuplādēt spraudmoduli",
    "endMedia":" Pēdējais elements",
    "endPage":" Pēdējā lapa",
    "firstMedia":" Pirmais elements",
    "firstPage":" Pirmā lapa",
    "fullscreen":" Pilnekrāna attēls",
    "nextMedia":" Nākamais elements",
    "nextPage":" Nākamā lapa",
    "noPlugin":"Formāts vai spraudmodulis neatbilst paredzētajiem",
    "pauseMedia":" Pauze",
    "playMedia":" Lasīt",
    "previousMedia":" Iepriekšējais elements",
    "previousPage":" Iepriekšējā lapa",
    "showMenuPage":" Izvēlēties redzamo elementu skaitu",
    "stopMedia":" Pārtraukt",
    "volumeMedia":" Skaļums",
    "wsDenied":" Tīmekļa pakalpojums pieļauj tikai vienu un to pašu domēnu.",
    "wsError":" Šis tīmekļa pakalpojums ir noslogots, mēģiniet vēlāk.",
    "wsLoading":" Lūdzu, uzgaidiet…",
    "wsMenuLoad":" Lūdzu, uzgaidiet…",
    "wsMenuOver":" Visi pieejamie tulkojumi",
    "wsRetry":" Nav atrasta neviena cita valoda",
    "wsSuccess":"Izvēlēties pieejamās valodas uznirstošajā logā",
    "wsTitle":" Visi pieejamie tulkojumi"
  },

  "mt":{
    "download":" Niżżel",
    "downloadPlugin":"Niżżel il-plug-in",
    "endMedia":" L-aħħar oġġett",
    "endPage":" L-aħħar paġna",
    "firstMedia":" L-ewwel oġġett",
    "firstPage":" L-ewwel paġna",
    "fullscreen":" Ara fl-iskrin kollu",
    "nextMedia":" L-oġġett li jmiss",
    "nextPage":" Il-paġna li jmiss",
    "noPlugin":"Format jew plug-in mhux disponibbli",
    "pauseMedia":" Pause",
    "playMedia":" Play",
    "previousMedia":" L-oġġett preċedenti",
    "previousPage":" Il-paġna preċedenti",
    "showMenuPage":" Agħżel in-numru ta' oġġetti li tixtieq tara",
    "stopMedia":" Waqqaf",
    "volumeMedia":" Volum",
    "wsDenied":" Is-servizz tal-web jippermettilek li tara l-istess domain biss",
    "wsError":" Is-servizz tal-web huwa okkupat, erġa pprova aktar tard",
    "wsLoading":" Jekk jogħġbok stenna…",
    "wsMenuLoad":" Jekk jogħġbok stenna…",
    "wsMenuOver":" Il-traduzzjonijiet disponibbli kollha",
    "wsRetry":" Ma nstabet l-ebda lingwa",
    "wsSuccess":"Agħżel il-lingwi disponibbli f'pop-up",
    "wsTitle":" Il-traduzzjonijiet disponibbli kollha"
  },

  "nl":{
    "download":"Downloaden",
    "downloadPlugin":"Download de plug-in",
    "endMedia":"Laatste item",
    "endPage":"Laatste bladzijde",
    "firstMedia":"Eerste item",
    "firstPage":"Eerste bladzijde",
    "fullscreen":"Openen in volledig scherm",
    "nextMedia":"Volgend item",
    "nextPage":"Volgende bladzijde",
    "noPlugin":"Formaat of plug-in niet ondersteund",
    "pauseMedia":"Pauzeren",
    "playMedia":"Spelen",
    "previousMedia":"Vorig item",
    "previousPage":"Vorige bladzijde",
    "showMenuPage":"Kies het aantal items dat u wilt zien.",
    "stopMedia":"Stoppen",
    "volumeMedia":"Volume",
    "wsDenied":"De webservice werkt niet buiten dit domein.",
    "wsError":"De webservice is overbelast, probeer het later opnieuw.",
    "wsLoading":"Even geduld…",
    "wsMenuLoad":"Even geduld…",
    "wsMenuOver":"Alle beschikbare vertalingen",
    "wsRetry":"Geen talen gevonden",
    "wsSuccess":"Klik om een taal te kiezen",
    "wsTitle":"Alle beschikbare vertalingen"
  },

  "pl":{
    "download":"Pobierz",
    "downloadPlugin":"Pobierz plug-in ",
    "endMedia":"Ostatni element",
    "endPage":"Ostatnia strona",
    "firstMedia":"Pierwszy element",
    "firstPage":"Pierwsza strona",
    "fullscreen":"Pełen ekran",
    "nextMedia":"Następny element",
    "nextPage":"Następna strona",
    "noPlugin":"Nieobsługiwany format lub plug-in ",
    "pauseMedia":"Zatrzymaj",
    "playMedia":"Odtwarzaj",
    "previousMedia":"Poprzedni element",
    "previousPage":"Poprzednia strona",
    "showMenuPage":"Wybierz liczbę elementów do wyświetlenia",
    "stopMedia":"Zakończ",
    "volumeMedia":"Głośność",
    "wsDenied":"Niespójność użytych domen",
    "wsError":"Serwis nie odpowiada, spróbuj później",
    "wsLoading":"Proszę czekać ",
    "wsMenuLoad":"Proszę czekać ",
    "wsMenuOver":"Wszystkie dostępne tłumaczenia",
    "wsRetry":"Nie znaleziono innych języków",
    "wsSuccess":"Wybierz język w menu rozwijanym",
    "wsTitle":"Wszystkie dostępne tłumaczenia"
  },

  "pt":{
    "download":"Descarregar",
    "downloadPlugin":"Descarregue o módulo de extensão",
    "endMedia":"Último elemento",
    "endPage":"Última página",
    "firstMedia":"Primeiro elemento",
    "firstPage":"Primeira página",
    "fullscreen":"Modo pleno ecrã",
    "nextMedia":"Elemento seguinte",
    "nextPage":"Página seguinte",
    "noPlugin":"Formato ou módulo de extensão não aceite",
    "pauseMedia":"Pausa",
    "playMedia":"Reproduzir",
    "previousMedia":"Elemento anterior",
    "previousPage":"Página anterior",
    "showMenuPage":"Escolher o número de elementos a visualizar",
    "stopMedia":"Parar",
    "volumeMedia":"Volume",
    "wsDenied":"O serviço Web só permite o mesmo domínio",
    "wsError":"Serviço Web ocupado. Tente mais tarde.",
    "wsLoading":"Aguarde…",
    "wsMenuLoad":"Aguarde…",
    "wsMenuOver":"Todas as traduções disponíveis",
    "wsRetry":"Nenhuma língua encontrada",
    "wsSuccess":"Escolha as línguas disponíveis na janela pop‑up",
    "wsTitle":"Todas as traduções disponíveis"
  },

  "ro":{
    "download":"Descarregar",
    "downloadPlugin":"Descărcare plug-in",
    "endMedia":"Último elemento",
    "endPage":"Última página",
    "firstMedia":"Primeiro elemento",
    "firstPage":"Primeira página",
    "fullscreen":"Modo pleno ecrã",
    "nextMedia":"Elemento seguinte",
    "nextPage":"Página seguinte",
    "noPlugin":"Format sau plug-in incompatibil",
    "pauseMedia":"Pausa",
    "playMedia":"Reproduzir",
    "previousMedia":"Elemento anterior",
    "previousPage":"Página anterior",
    "showMenuPage":"Escolher o número de elementos a visualizar",
    "stopMedia":"Parar",
    "volumeMedia":"Volume",
    "wsDenied":"O serviço Web só permite o mesmo domínio",
    "wsError":"Serviço Web ocupado. Tente mais tarde.",
    "wsLoading":"Aguarde…",
    "wsMenuLoad":"Aguarde…",
    "wsMenuOver":"Todas as traduções disponíveis",
    "wsRetry":"Nenhuma língua encontrada",
    "wsSuccess":"Alegeţi limba",
    "wsTitle":"Todas as traduções disponíveis"
  },

  "sk":{
    "download":"Stiahnuť",
    "downloadPlugin":"Stiahnuť doplňujúci modul",
    "endMedia":"Posledná položka",
    "endPage":"Posledná stránka",
    "firstMedia":"Prvá položka",
    "firstPage":"Prvá stránka",
    "fullscreen":"Zobraziť na celú obrazovku",
    "nextMedia":"Ďalšia položka",
    "nextPage":"Ďalšia stránka",
    "noPlugin":"Formát alebo doplňujúci modul nie je podporovaný",
    "pauseMedia":"Prerušiť",
    "playMedia":"Prehrať",
    "previousMedia":"Predchádzajúca položka",
    "previousPage":"Predchádzajúca stránka",
    "showMenuPage":"Zvoľte počet zobrazovaných položiek",
    "stopMedia":"Zastaviť",
    "volumeMedia":"Hlasitosť",
    "wsDenied":"Webová služba povoľuje iba rovnakú doménu",
    "wsError":"Webová služba je preťažená, vyskúšajte neskôr",
    "wsLoading":"Čakajte, prosím...",
    "wsMenuLoad":"Čakajte, prosím...",
    "wsMenuOver":"Všetky dostupné preklady",
    "wsRetry":"Preklady do iných jazykov nenájdené",
    "wsSuccess":"Vyberte si z dostupných jazykov v zozname",
    "wsTitle":"Všetky dostupné preklady"
  },

  "sl":{
    "download":"Prenesi",
    "downloadPlugin":"Prenos dodatka",
    "endMedia":"Zadnji zadetek",
    "endPage":"Zadnja stran ",
    "firstMedia":"Prvi zadetek",
    "firstPage":" Prva stran",
    "fullscreen":"Prikaz v polni velikosti",
    "nextMedia":"Naslednji zadetek",
    "nextPage":" Naslednja stran",
    "noPlugin":"Oblika ali dodatek nista podprta",
    "pauseMedia":"Prekini",
    "playMedia":"Predvajaj",
    "previousMedia":"Prejšnji zadetek",
    "previousPage":"Prejšnja stran ",
    "showMenuPage":" Izberi število prikazanih zadetkov",
    "stopMedia":"Ustavi",
    "volumeMedia":"Glasnost",
    "wsDenied":"Spletna storitev omogoča samo prikaz strani iste domene ",
    "wsError":"Spletna storitev trenutno ni na voljo. Poskusite znova kasneje.",
    "wsLoading":"Počakajte trenutek.",
    "wsMenuLoad":"Počakajte trenutek.",
    "wsMenuOver":"Vsi razpoložljivi prevodi",
    "wsRetry":"Drugi jeziki niso na voljo",
    "wsSuccess":"Izbira jezika v pojavnem oknu",
    "wsTitle":"Vsi razpoložljivi prevodi"
  },

  "sv":{
    "download":"Ladda ner",
    "downloadPlugin":"Ladda ner insticksprogrammet",
    "endMedia":"Sista objektet",
    "endPage":"Sista sidan",
    "firstMedia":"Första objektet",
    "firstPage":"Första sidan",
    "fullscreen":"Visa i fullskärm",
    "nextMedia":"Nästa objekt",
    "nextPage":"Nästa sida",
    "noPlugin":"Formatet eller insticksprogrammet stöds inte",
    "pauseMedia":"Paus",
    "playMedia":"Spela",
    "previousMedia":"Föregående objekt",
    "previousPage":"Föregående sida",
    "showMenuPage":"Ange hur många objekt som ska visas",
    "stopMedia":"Stopp",
    "volumeMedia":"Volym",
    "wsDenied":"Webbtjänsten fungerar bara inom en och samma domän",
    "wsError":"Webbtjänsten är upptagen, försök igen senare",
    "wsLoading":"Var god vänta…",
    "wsMenuLoad":"Var god vänta…",
    "wsMenuOver":"Alla tillgängliga språkversioner",
    "wsRetry":"Hittar inga andra språk",
    "wsSuccess":"Välj språk i en snabbmeny",
    "wsTitle":"Alla tillgängliga språkversioner"
  }

}