define({
    "webs.bldr.canvas.drag.msg": "Drag above, below or to the sides of any module.",
    "webs.bldr.canvas.pages.delete.msg": "To remove a page section, change your page layout here",
    "webs.bldr.canvas.titlebar.delete": "Delete",
    "webs.bldr.canvas.titlebar.drag": "Drag to Move",
    "webs.bldr.canvas.titlebar.settings": "Settings",
    "webs.bldr.chome.settings.navbar.add": "Add To Navbar",
    "webs.bldr.chrome.app.editorDialogDefaultTitle": "Options",
    "webs.bldr.chrome.app.hideHelp": "Hide Help Boxes",
    "webs.bldr.chrome.app.premiumDialogHeading": "Upgrade Today!",
    "webs.bldr.chrome.app.showHelp": "Show Help Boxes",
    "webs.bldr.chrome.app.toggleNavBarError": "There was an error submitting your changes.",
    "webs.bldr.chrome.module.config": "Choose Module Configuration",
    "webs.bldr.chrome.preivew": "Preview",
    "webs.bldr.chrome.preview": "Preview",
    "webs.bldr.chrome.preview.loading": "Please wait, loading your site builder",
    "webs.bldr.chrome.preview.tooltip": "Preview Site",
    "webs.bldr.chrome.redo": "Redo",
    "webs.bldr.chrome.redo.tooltip": "Redo Changes",
    "webs.bldr.chrome.seo.checklist": "SEO Optimizer Checklist",
    "webs.bldr.chrome.seo.default": "SEO: {percent}%",
    "webs.bldr.chrome.seo.name": "SEO",
    "webs.bldr.chrome.settings.changelayout": "Change Page Layout",
    "webs.bldr.chrome.settings.createpage": "Create a New Page",
    "webs.bldr.chrome.settings.deleteApp": "Delete App",
    "webs.bldr.chrome.settings.deleteApp.tooltip": "Remove From Navbar",
    "webs.bldr.chrome.settings.header": "Settings",
    "webs.bldr.chrome.settings.metatags": "MetaTags/Description",
    "webs.bldr.chrome.settings.metatags.tooltip": "Update title/tags/description",
    "webs.bldr.chrome.settings.navbar.hide": "Hide From Navbar",
    "webs.bldr.chrome.settings.navbar.home": "Home",
    "webs.bldr.chrome.settings.navbar.more": "More",
    "webs.bldr.chrome.settings.navbar.show": "Show In Navbar",
    "webs.bldr.chrome.settings.password": "Password Protection",
    "webs.bldr.chrome.settings.rename": "Rename Page",
    "webs.bldr.chrome.settings.rename.tooltip": "Rename Page",
    "webs.bldr.chrome.settings.revert": "Revert to Published",
    "webs.bldr.chrome.settings.revert.tooltip": "Revert All Changes",
    "webs.bldr.chrome.settings.tooltip": "Page Settings",
    "webs.bldr.chrome.settings.tour": "SiteBuilder Tour",
    "webs.bldr.chrome.undo": "Undo",
    "webs.bldr.chrome.undo.tooltip": "Undo Changes",
    "webs.bldr.dialog.image.autoattributionlink": "An attribution link will automatically be added to your site.",
    "webs.bldr.dialog.image.choosepreviouslystored": "Choose an image you&rsquo;ve previously stored on our site",
    "webs.bldr.dialog.image.choosepreviouslyuploaded": "Choose a previously-uploaded image",
    "webs.bldr.dialog.image.clickformore": "Click for more images",
    "webs.bldr.dialog.image.didnotsearchyet": "You have not searched for images yet. Please enter your search now.",
    "webs.bldr.dialog.image.fileuploading": "File uploading...",
    "webs.bldr.dialog.image.flickrcc": "Flickr/Creative Commons",
    "webs.bldr.dialog.image.flickrtextplaceholder": "Enter a keyword search",
    "webs.bldr.dialog.image.freeimages": "Free Images",
    "webs.bldr.dialog.image.imagenotfound": "Image<br>Not<br>Found",
    "webs.bldr.dialog.image.imagepreview": "Image Preview",
    "webs.bldr.dialog.image.imagepreviewalt": "Preview of the image at the entered url",
    "webs.bldr.dialog.image.imageurl": "Image URL",
    "webs.bldr.dialog.image.imageurlexample": "Example: http://www.w3schools.com/html/w3schools.jpg<br/>Images <strong><em>must be<\/em><\/strong> jpg, gif or png.",
    "webs.bldr.dialog.image.insertimage": "Insert Image",
    "webs.bldr.dialog.image.insertimageurl": "Insert an image from another website by providing the image URL.",
    "webs.bldr.dialog.image.myimages": "My Images",
    "webs.bldr.dialog.image.nouploadedimage": "You currently have no images uploaded. To get started click the upload button.",
    "webs.bldr.dialog.image.pleaseselectimagefile": "Please select an image file.",
    "webs.bldr.dialog.image.preview": "Preview",
    "webs.bldr.dialog.image.previewimageurl": "Preview this Image URL",
    "webs.bldr.dialog.image.problemuploadingimage": "There was a problem uploading your file, please refresh the page and try again",
    "webs.bldr.dialog.image.search": "Search",
    "webs.bldr.dialog.image.searchflickr": "Search Flickr",
    "webs.bldr.dialog.image.searchflickrcc": "Search Flickr&rsquo;s Creative Commons.",
    "webs.bldr.dialog.image.uploadfile": "Upload File",
    "webs.bldr.dialog.image.uploadimage": "Upload Image",
    "webs.bldr.dialog.image.uploadnewimage": "Upload a New Image",
    "webs.bldr.dialog.link.email.emailPrompt": "Email Address:",
    "webs.bldr.dialog.link.email.header": "Link to an email address",
    "webs.bldr.dialog.link.email.hint": "(ex. name@email.com)",
    "webs.bldr.dialog.link.email.placeholder": "enter an email address",
    "webs.bldr.dialog.link.file.oldInternal.header": "Link to a file download",
    "webs.bldr.dialog.link.file.oldInternal.myFiles": "My Files",
    "webs.bldr.dialog.link.file.oldInternal.searchPlaceholder": "Type keyword(s) and press enter",
    "webs.bldr.dialog.link.file.oldInternal.upload": "Upload New",
    "webs.bldr.dialog.link.insertLink": "Insert Link",
    "webs.bldr.dialog.link.lightbox.caption": "Caption:",
    "webs.bldr.dialog.link.lightbox.captionPlaceholder": "Enter a caption... (optional)",
    "webs.bldr.dialog.link.lightbox.enableLightbox": "Enable Lightbox",
    "webs.bldr.dialog.link.lightbox.header": "Display a full screen version of your image when clicked",
    "webs.bldr.dialog.link.myPages.header": "Link to another page on your website",
    "webs.bldr.dialog.link.myPages.pageLabel": "Page:",
    "webs.bldr.dialog.link.popover.heading": "Change Link",
    "webs.bldr.dialog.link.tab.email": "Email",
    "webs.bldr.dialog.link.tab.file": "File",
    "webs.bldr.dialog.link.tab.lightbox": "Lightbox",
    "webs.bldr.dialog.link.tab.myPages": "My Pages",
    "webs.bldr.dialog.link.tab.webpage": "Webpage",
    "webs.bldr.dialog.link.tab.webpage.hint": "(ex. http://www.relatedwebsite.com)",
    "webs.bldr.dialog.link.webpage.header": "Link to an external webpage",
    "webs.bldr.dialog.link.webpage.openInNewWindow": "New Window:",
    "webs.bldr.dialog.link.webpage.webpageLabel": "Web address:",
    "webs.bldr.dialog.publish.beingPublish": "Please wait while your website is being published",
    "webs.bldr.dialog.publish.domainCoupon.successfullyPublishedMessage": "Congratulations! You have successfully published your website.",
    "webs.bldr.dialog.publish.premium.successfullyPublishedMessage": "Congratulations! You have successfully published your website.",
    "webs.bldr.dialog.publish.publishAllPages": "Publish all pages",
    "webs.bldr.dialog.publish.publishError": "Sorry, we were unable to publish your site, please try again in a few minutes!",
    "webs.bldr.dialog.publish.publishSaleDayTitle": "Published. Today's a Sale Day!",
    "webs.bldr.dialog.publish.publishTitle": "Publish",
    "webs.bldr.dialog.publish.publishToInternetOrSaveAsDraft": "Would you like to publish your changes to the Internet or Save as a draft and Exit?",
    "webs.bldr.dialog.publish.sale.successfullyPublishedMessage": "Congratulations! You have successfully published your website.",
    "webs.bldr.dialog.publish.saleSingle.successfullyPublishedMessage": "Congratulations! You have successfully published your website.",
    "webs.bldr.dialog.publish.successfullyPublishedMessage": "Congratulations! You have successfully published your website.",
    "webs.bldr.dialog.publish.turing.header": "Before we add your site to the web, we need to make sure you're not a robot. Just play this quick game to prove it.",
    "webs.bldr.dialog.publish.turing.submit": "Submit",
    "webs.bldr.dialog.publish.turing.title": "Just One More Step!",
    "webs.bldr.dialog.publish.turing.try_again": "Sorry, please try again.",
    "webs.bldr.dialog.publish.unableToPublish": "Sorry, we were unable to publish your site, please try again in a few minutes!",
    "webs.bldr.dialog.publish.vpCallingCardTitle": "Get 250 matching business cards for $10",
    "webs.bldr.dock.ads.appfeeds": "Other",
    "webs.bldr.dock.ads.appfeeds.buttonText": "Visit Our App Store",
    "webs.bldr.dock.ads.appfeeds.text": "Blogs, Calendars &amp; More Apps.",
    "webs.bldr.dock.ads.webstore.buttonText": "Install our Web Store App",
    "webs.bldr.dock.ads.webstore.text": "Want to build an Online Store?",
    "webs.bldr.dock.controls.toggle_dock": "Toggle Dock",
    "webs.bldr.dock.controls.toggle_grid": "Toggle Grid",
    "webs.bldr.image.max_container_width": "You have reached the maximum width in this container.",
    "webs.bldr.image.max_height": "You have reached the maximum height of your image.",
    "webs.bldr.image.max_resolution": "You've reached the maximum resolution of your image.",
    "webs.bldr.image.max_sidebar_width": "You have reached the maximum width in your sidebar.",
    "webs.bldr.image.max_width": "You have reached the maximum width of your image.",
    "webs.bldr.modules.2-columns": "2 Columns",
    "webs.bldr.modules.3-columns": "3 Columns",
    "webs.bldr.modules.ads.toolbar.tooltip": "Use the buttons on the right to edit your ad.",
    "webs.bldr.modules.audio": "Audio",
    "webs.bldr.modules.audio.toolbar.Advanced Settings": "Advanced Settings",
    "webs.bldr.modules.audio.toolbar.Autoplay": "Autoplay",
    "webs.bldr.modules.audio.toolbar.Color": "Color",
    "webs.bldr.modules.audio.toolbar.Dark": "Dark",
    "webs.bldr.modules.audio.toolbar.Large": "Large",
    "webs.bldr.modules.audio.toolbar.Light": "Light",
    "webs.bldr.modules.audio.toolbar.Scheme": "Scheme",
    "webs.bldr.modules.audio.toolbar.Settings": "Settings",
    "webs.bldr.modules.audio.toolbar.Size": "Size",
    "webs.bldr.modules.audio.toolbar.Small": "Small",
    "webs.bldr.modules.audio.toolbar.Upload Audio": "Upload Audio",
    "webs.bldr.modules.audio.toolbar.dark": "dark",
    "webs.bldr.modules.audio.toolbar.large": "large",
    "webs.bldr.modules.audio.toolbar.light": "light",
    "webs.bldr.modules.audio.toolbar.small": "small",
    "webs.bldr.modules.audio.toolbar.tooltip": "Use the buttons on the right to edit your audio.",
    "webs.bldr.modules.buckets": "Combo",
    "webs.bldr.modules.button": "Button",
    "webs.bldr.modules.button.toolbar.Background": "Background",
    "webs.bldr.modules.button.toolbar.Bold": "Bold",
    "webs.bldr.modules.button.toolbar.Button Color": "Button Color",
    "webs.bldr.modules.button.toolbar.Center": "Center",
    "webs.bldr.modules.button.toolbar.Decrease Font Size": "Decrease Font Size",
    "webs.bldr.modules.button.toolbar.Icon": "Icon",
    "webs.bldr.modules.button.toolbar.Increase Font Size": "Increase Font Size",
    "webs.bldr.modules.button.toolbar.Italic": "Italic",
    "webs.bldr.modules.button.toolbar.Left": "Left",
    "webs.bldr.modules.button.toolbar.Link": "Link",
    "webs.bldr.modules.button.toolbar.Right": "Right",
    "webs.bldr.modules.button.toolbar.Text Color": "Text Color",
    "webs.bldr.modules.button.toolbar.Underline": "Underline",
    "webs.bldr.modules.button.toolbar.icon": "icon",
    "webs.bldr.modules.button.toolbar.tooltip": "Use the buttons on the right to edit your button.",
    "webs.bldr.modules.carousel_image.toolbar.tooltip": "Use the buttons on the right to edit your carousel image.",
    "webs.bldr.modules.columns": "Columns",
    "webs.bldr.modules.contact_form": "Contact Form",
    "webs.bldr.modules.contact_form.toolbar.Edit Form": "Edit Form",
    "webs.bldr.modules.contact_form.toolbar.tooltip": "Use the buttons on the right to edit your contact form.",
    "webs.bldr.modules.container.Apps": "Apps",
    "webs.bldr.modules.container.Pages": "Pages",
    "webs.bldr.modules.container.commerce": "Commerce",
    "webs.bldr.modules.container.general": "General",
    "webs.bldr.modules.container.layout": "Layout",
    "webs.bldr.modules.container.media": "Media",
    "webs.bldr.modules.container.popular": "Popular",
    "webs.bldr.modules.container.social": "Social",
    "webs.bldr.modules.container.structure": "Structure",
    "webs.bldr.modules.container.zumba": "Zumba",
    "webs.bldr.modules.dialog.toolbar.tooltip": "Use the buttons on the right to edit your dialog.",
    "webs.bldr.modules.donate": "PayPal Donate",
    "webs.bldr.modules.donate.toolbar.Edit Button": "Edit Button",
    "webs.bldr.modules.donate.toolbar.tooltip": "Use the buttons on the right to edit your donate.",
    "webs.bldr.modules.email_list": "Subscribe",
    "webs.bldr.modules.fb-comments": "FB Comments",
    "webs.bldr.modules.fb-comments.toolbar.# of Posts": "# of Posts",
    "webs.bldr.modules.fb-comments.toolbar.Color Scheme": "Color Scheme",
    "webs.bldr.modules.fb-comments.toolbar.Dark": "Dark",
    "webs.bldr.modules.fb-comments.toolbar.Light": "Light",
    "webs.bldr.modules.fb-comments.toolbar.Settings": "Settings",
    "webs.bldr.modules.fb-comments.toolbar.dark": "dark",
    "webs.bldr.modules.fb-comments.toolbar.light": "light",
    "webs.bldr.modules.fb-comments.toolbar.tooltip": "Use the buttons on the right to edit your Facebook comments.",
    "webs.bldr.modules.fb-like": "FB Like Box",
    "webs.bldr.modules.fb-like.toolbar.Advanced Settings": "Advanced Settings",
    "webs.bldr.modules.fb-like.toolbar.Border Color": "Border Color",
    "webs.bldr.modules.fb-like.toolbar.Color Scheme": "Color Scheme",
    "webs.bldr.modules.fb-like.toolbar.Dark": "Dark",
    "webs.bldr.modules.fb-like.toolbar.Facebook URL": "Facebook URL",
    "webs.bldr.modules.fb-like.toolbar.Light": "Light",
    "webs.bldr.modules.fb-like.toolbar.Settings": "Settings",
    "webs.bldr.modules.fb-like.toolbar.Show&nbsp;Faces": "Show&nbsp;Faces",
    "webs.bldr.modules.fb-like.toolbar.Show&nbsp;Header": "Show&nbsp;Header",
    "webs.bldr.modules.fb-like.toolbar.Show&nbsp;Stream": "Show&nbsp;Stream",
    "webs.bldr.modules.fb-like.toolbar.dark": "dark",
    "webs.bldr.modules.fb-like.toolbar.light": "light",
    "webs.bldr.modules.fb-like.toolbar.tooltip": "Use the buttons on the right to edit your FB like module.",
    "webs.bldr.modules.follow": "Follow",
    "webs.bldr.modules.follow.toolbar.Advanced Settings": "Advanced Settings",
    "webs.bldr.modules.follow.toolbar.Button Size": "Button Size",
    "webs.bldr.modules.follow.toolbar.Follower Count": "Follower Count",
    "webs.bldr.modules.follow.toolbar.Large": "Large",
    "webs.bldr.modules.follow.toolbar.Medium": "Medium",
    "webs.bldr.modules.follow.toolbar.Settings": "Settings",
    "webs.bldr.modules.follow.toolbar.Twitter Username": "Twitter Username",
    "webs.bldr.modules.follow.toolbar.large": "large",
    "webs.bldr.modules.follow.toolbar.medium": "medium",
    "webs.bldr.modules.follow.toolbar.tooltip": "Use the buttons on the right to edit your follow widget.",
    "webs.bldr.modules.google_checkout": "Google",
    "webs.bldr.modules.google_checkout.toolbar.Edit Button": "Edit Button",
    "webs.bldr.modules.google_checkout.toolbar.tooltip": "Use the buttons on the right to edit your google checkout.",
    "webs.bldr.modules.google_map": "Map",
    "webs.bldr.modules.google_map.toolbar.Address": "Address",
    "webs.bldr.modules.google_map.toolbar.Advanced Settings": "Advanced Settings",
    "webs.bldr.modules.google_map.toolbar.Color": "Color",
    "webs.bldr.modules.google_map.toolbar.Frame": "Frame",
    "webs.bldr.modules.google_map.toolbar.Get&nbsp;Directions": "Get&nbsp;Directions",
    "webs.bldr.modules.google_map.toolbar.Settings": "Settings",
    "webs.bldr.modules.google_map.toolbar.Show&nbsp;Controls": "Show&nbsp;Controls",
    "webs.bldr.modules.google_map.toolbar.Show&nbsp;Marker": "Show&nbsp;Marker",
    "webs.bldr.modules.google_map.toolbar.tooltip": "Use the buttons on the right to edit your google map.",
    "webs.bldr.modules.header_editor.toolbar.addContent": "+ Content",
    "webs.bldr.modules.header_editor.toolbar.tooltip": "Use the buttons on the right to edit your header.",
    "webs.bldr.modules.header_layer_image.toolbar.tooltip": "Use the buttons on the right to edit your header image.",
    "webs.bldr.modules.header_layer_logo.toolbar.tooltip": "Use the buttons on the right to edit your header logo.",
    "webs.bldr.modules.header_text.toolbar.tooltip": "Use the buttons on the right to edit your header text.",
    "webs.bldr.modules.horizontal_rule": "Divider",
    "webs.bldr.modules.horizontal_rule.toolbar.Advanced": "Advanced",
    "webs.bldr.modules.horizontal_rule.toolbar.Center": "Center",
    "webs.bldr.modules.horizontal_rule.toolbar.Divider Styles": "Divider Styles",
    "webs.bldr.modules.horizontal_rule.toolbar.Left": "Left",
    "webs.bldr.modules.horizontal_rule.toolbar.Margin": "Margin",
    "webs.bldr.modules.horizontal_rule.toolbar.Position": "Position",
    "webs.bldr.modules.horizontal_rule.toolbar.Right": "Right",
    "webs.bldr.modules.horizontal_rule.toolbar.Style": "Style",
    "webs.bldr.modules.horizontal_rule.toolbar.Styles": "Styles",
    "webs.bldr.modules.horizontal_rule.toolbar.Width": "Width",
    "webs.bldr.modules.horizontal_rule.toolbar.center": "center",
    "webs.bldr.modules.horizontal_rule.toolbar.left": "left",
    "webs.bldr.modules.horizontal_rule.toolbar.right": "right",
    "webs.bldr.modules.horizontal_rule.toolbar.tooltip": "Use the buttons on the right to edit your Divider.",
    "webs.bldr.modules.html": "Custom HTML",
    "webs.bldr.modules.html.toolbar.Edit HTML": "Edit HTML",
    "webs.bldr.modules.html.toolbar.tooltip": "Use the buttons on the right to edit your html.",
    "webs.bldr.modules.image": "Image",
    "webs.bldr.modules.image.toolbar.Center": "Center",
    "webs.bldr.modules.image.toolbar.Change Background": "Change Background",
    "webs.bldr.modules.image.toolbar.Change Image": "Change Image",
    "webs.bldr.modules.image.toolbar.Change Logo": "Change Logo",
    "webs.bldr.modules.image.toolbar.Frame": "Frame",
    "webs.bldr.modules.image.toolbar.Left": "Left",
    "webs.bldr.modules.image.toolbar.Link": "Link",
    "webs.bldr.modules.image.toolbar.Right": "Right",
    "webs.bldr.modules.image.toolbar.tooltip": "Use the buttons on the right to edit your image.",
    "webs.bldr.modules.paragraph": "Paragraph",
    "webs.bldr.modules.paypal": "PayPal Buy Now",
    "webs.bldr.modules.paypal.toolbar.Edit Button": "Edit Button",
    "webs.bldr.modules.paypal.toolbar.tooltip": "Use the buttons on the right to edit your paypal.",
    "webs.bldr.modules.photo_gallery": "Photo Gallery",
    "webs.bldr.modules.photo_gallery-ramp.toolbar.tooltip": "Use the buttons on the right to edit your photo gallery",
    "webs.bldr.modules.photo_gallery.toolbar.tooltip": "Use the buttons on the right to edit your photo gallery",
    "webs.bldr.modules.photo_gallery_slideshow": "Slideshow 2",
    "webs.bldr.modules.photo_gallery_slideshow.toolbar.tooltip": "Use the buttons on the right to edit your slideshow",
    "webs.bldr.modules.sb2_paragraph.toolbar.Edit Paragraph": "Edit Paragraph",
    "webs.bldr.modules.sb2_paragraph.toolbar.tooltip": "Use the buttons on the right to edit your paragraph.",
    "webs.bldr.modules.share_button": "Share",
    "webs.bldr.modules.share_button.toolbar.Advanced Settings": "Advanced Settings",
    "webs.bldr.modules.share_button.toolbar.Settings": "Settings",
    "webs.bldr.modules.share_button.toolbar.Show&nbsp;Email": "Show&nbsp;Email",
    "webs.bldr.modules.share_button.toolbar.Show&nbsp;Google&nbsp;Plus": "Show&nbsp;Google&nbsp;Plus",
    "webs.bldr.modules.share_button.toolbar.Show&nbsp;Like": "Show&nbsp;Like",
    "webs.bldr.modules.share_button.toolbar.Show&nbsp;More": "Show&nbsp;More",
    "webs.bldr.modules.share_button.toolbar.Show&nbsp;Tweet": "Show&nbsp;Tweet",
    "webs.bldr.modules.share_button.toolbar.tooltip": "Use the buttons on the right to edit your share button.",
    "webs.bldr.modules.slideshow": "Slideshow",
    "webs.bldr.modules.slideshow.toolbar.1 Second": "1 Second",
    "webs.bldr.modules.slideshow.toolbar.1000": "1000",
    "webs.bldr.modules.slideshow.toolbar.2 Seconds": "2 Seconds",
    "webs.bldr.modules.slideshow.toolbar.2000": "2000",
    "webs.bldr.modules.slideshow.toolbar.3 Seconds": "3 Seconds",
    "webs.bldr.modules.slideshow.toolbar.3000": "3000",
    "webs.bldr.modules.slideshow.toolbar.4 Seconds": "4 Seconds",
    "webs.bldr.modules.slideshow.toolbar.4000": "4000",
    "webs.bldr.modules.slideshow.toolbar.5 Seconds": "5 Seconds",
    "webs.bldr.modules.slideshow.toolbar.5000": "5000",
    "webs.bldr.modules.slideshow.toolbar.Autoplay": "Autoplay",
    "webs.bldr.modules.slideshow.toolbar.Background": "Background",
    "webs.bldr.modules.slideshow.toolbar.Color": "Color",
    "webs.bldr.modules.slideshow.toolbar.Fade": "Fade",
    "webs.bldr.modules.slideshow.toolbar.H Carousel": "H Carousel",
    "webs.bldr.modules.slideshow.toolbar.H Slide": "H Slide",
    "webs.bldr.modules.slideshow.toolbar.Manage Slideshow": "Manage Slideshow",
    "webs.bldr.modules.slideshow.toolbar.None": "None",
    "webs.bldr.modules.slideshow.toolbar.Puff": "Puff",
    "webs.bldr.modules.slideshow.toolbar.Settings": "Settings",
    "webs.bldr.modules.slideshow.toolbar.Slideshow Settings": "Slideshow Settings",
    "webs.bldr.modules.slideshow.toolbar.Speed": "Speed",
    "webs.bldr.modules.slideshow.toolbar.Transition": "Transition",
    "webs.bldr.modules.slideshow.toolbar.V Carousel": "V Carousel",
    "webs.bldr.modules.slideshow.toolbar.V Slide": "V Slide",
    "webs.bldr.modules.slideshow.toolbar.carouselHorizontal": "carouselHorizontal",
    "webs.bldr.modules.slideshow.toolbar.carouselVertical": "carouselVertical",
    "webs.bldr.modules.slideshow.toolbar.fade": "fade",
    "webs.bldr.modules.slideshow.toolbar.none": "none",
    "webs.bldr.modules.slideshow.toolbar.puff": "puff",
    "webs.bldr.modules.slideshow.toolbar.slideHorizontal": "slideHorizontal",
    "webs.bldr.modules.slideshow.toolbar.slideVertical": "slideVertical",
    "webs.bldr.modules.slideshow.toolbar.tooltip": "Use the buttons on the right to edit your slideshow.",
    "webs.bldr.modules.social-links": "Social Links",
    "webs.bldr.modules.social-links.toolbar.tooltip": "Use the buttons on the right to edit your social links.",
    "webs.bldr.modules.spacer": "Spacer",
    "webs.bldr.modules.table": "Table",
    "webs.bldr.modules.text": "Text",
    "webs.bldr.modules.text.toolbar.1": " 2",
    "webs.bldr.modules.text.toolbar.<span style='text-transform:none;'>a": " b",
    "webs.bldr.modules.text.toolbar.<span style='text-transform:none;'>i": " ii",
    "webs.bldr.modules.text.toolbar.A": " B",
    "webs.bldr.modules.text.toolbar.Align Center": "Align Center",
    "webs.bldr.modules.text.toolbar.Align Justify": "Align Justify",
    "webs.bldr.modules.text.toolbar.Align Left": "Align Left",
    "webs.bldr.modules.text.toolbar.Align Right": "Align Right",
    "webs.bldr.modules.text.toolbar.Bold": "Bold",
    "webs.bldr.modules.text.toolbar.Clear": "Clear",
    "webs.bldr.modules.text.toolbar.Clear Formatting": "Clear Formatting",
    "webs.bldr.modules.text.toolbar.Click on your text to edit it": "Click on your text to edit it",
    "webs.bldr.modules.text.toolbar.Color": "Color",
    "webs.bldr.modules.text.toolbar.Decrease Font Size": "Decrease Font Size",
    "webs.bldr.modules.text.toolbar.I": " II",
    "webs.bldr.modules.text.toolbar.Increase Font Size": "Increase Font Size",
    "webs.bldr.modules.text.toolbar.Indent": "Indent",
    "webs.bldr.modules.text.toolbar.Italic": "Italic",
    "webs.bldr.modules.text.toolbar.Link": "Link",
    "webs.bldr.modules.text.toolbar.List": "List",
    "webs.bldr.modules.text.toolbar.None": "None",
    "webs.bldr.modules.text.toolbar.Outdent": "Outdent",
    "webs.bldr.modules.text.toolbar.Strikethrough": "Strikethrough",
    "webs.bldr.modules.text.toolbar.Text Color": "Text Color",
    "webs.bldr.modules.text.toolbar.Underline": "Underline",
    "webs.bldr.modules.text.toolbar.tooltip": "Use the buttons on the right to edit your text.",
    "webs.bldr.modules.text_condensed.toolbar.tooltip": "Use the buttons on the right to edit your text.",
    "webs.bldr.modules.text_fonts.toolbar.tooltip": "Use the buttons on the right to edit your text.",
    "webs.bldr.modules.text_image": "Image &amp; Text",
    "webs.bldr.modules.title": "Title",
    "webs.bldr.modules.title.toolbar.Align Center": "Align Center",
    "webs.bldr.modules.title.toolbar.Align Left": "Align Left",
    "webs.bldr.modules.title.toolbar.Align Right": "Align Right",
    "webs.bldr.modules.title.toolbar.Bold": "Bold",
    "webs.bldr.modules.title.toolbar.Clear Formatting": "Clear Formatting",
    "webs.bldr.modules.title.toolbar.Color": "Color",
    "webs.bldr.modules.title.toolbar.Decrease Font Size": "Decrease Font Size",
    "webs.bldr.modules.title.toolbar.Icon": "Icon",
    "webs.bldr.modules.title.toolbar.Increase Font Size": "Increase Font Size",
    "webs.bldr.modules.title.toolbar.Italic": "Italic",
    "webs.bldr.modules.title.toolbar.Link": "Link",
    "webs.bldr.modules.title.toolbar.Strikethrough": "Strikethrough",
    "webs.bldr.modules.title.toolbar.Text Color": "Text Color",
    "webs.bldr.modules.title.toolbar.Underline": "Underline",
    "webs.bldr.modules.title.toolbar.tooltip": "Use the buttons on the right to edit your title.",
    "webs.bldr.modules.title_condensed.toolbar.tooltip": "Use the buttons on the right to edit your title.",
    "webs.bldr.modules.twitter-feed": "Twitter Feed",
    "webs.bldr.modules.twitter-feed.toolbar.tooltip": "Use the buttons on the right to edit your twitter feed.",
    "webs.bldr.modules.video": "Video",
    "webs.bldr.modules.video.toolbar.tooltip": "Use the buttons on the right to edit your video.",
    "webs.bldr.modules.webstore_products": "Products",
    "webs.bldr.modules.webstore_products.toolbar.tooltip": "Use the buttons on the right to edit your products.",
    "webs.bldr.modules.zumba_calendar": "Calendar",
    "webs.bldr.modules.zumba_contact": "Contact Form",
    "webs.bldr.modules.zumba_licenses": "Licenses",
    "webs.bldr.modules.zumba_membership": "Tenure",
    "webs.bldr.modules.zumba_qualifications": "Qualifications",
    "webs.bldr.modules.zumba_shop": "Shop",
    "webs.bldr.placeholder.body": "Drag & Drop Modules Here",
    "webs.bldr.placeholder.default": "Drop a Module Here",
    "webs.bldr.placeholder.footer": "Drag Modules into Footer Here",
    "webs.bldr.placeholder.sidebar": "Drag Modules into Sidebar Here",
    "webs.bldr.placeholder.subfooter": "Drag Modules into Subfooter Here",
    "webs.bldr.preview.close": "Close",
    "webs.bldr.preview.currentlyViewing": "You are currently viewing:",
    "webs.bldr.preview.previewVersion": "Preview Version",
    "webs.bldr.preview.publishedVersion": "Published Version",
    "webs.bldr.start.text": "Drag and drop modules into the main content area of your page.",
    "webs.bldr.start.title": "Let's start building!",
    "webs.bldr.toolbar.11": "11",
    "webs.bldr.toolbar.14": "14",
    "webs.bldr.toolbar.fonts.all": "All Fonts",
    "webs.bldr.toolbar.fonts.default": "Default Font",
    "webs.bldr.toolbar.fonts.recent": "Recent Fonts",
    "webs.bldr.toolbar.text.#ofPosts": "# of Posts",
    "webs.bldr.toolbar.text.+Column": "+Column",
    "webs.bldr.toolbar.text.+Content": "+ Content",
    "webs.bldr.toolbar.text.+Image": "+ Image",
    "webs.bldr.toolbar.text.+Row": "+Row",
    "webs.bldr.toolbar.text.+Text": "+ Text",
    "webs.bldr.toolbar.text.0": "0",
    "webs.bldr.toolbar.text.1": "1",
    "webs.bldr.toolbar.text.1,2,3": "1, 2, 3...",
    "webs.bldr.toolbar.text.1,2,3&hellip;": "1, 2, 3&hellip;",
    "webs.bldr.toolbar.text.10": "10",
    "webs.bldr.toolbar.text.100%": "100%",
    "webs.bldr.toolbar.text.1000": "1000",
    "webs.bldr.toolbar.text.11": "11",
    "webs.bldr.toolbar.text.12": "12",
    "webs.bldr.toolbar.text.14": "14",
    "webs.bldr.toolbar.text.16": "16",
    "webs.bldr.toolbar.text.18": "18",
    "webs.bldr.toolbar.text.1Second": "1 Second",
    "webs.bldr.toolbar.text.2": "2",
    "webs.bldr.toolbar.text.2000": "2000",
    "webs.bldr.toolbar.text.24": "24",
    "webs.bldr.toolbar.text.2Seconds": "2 Seconds",
    "webs.bldr.toolbar.text.3": "3",
    "webs.bldr.toolbar.text.3000": "3000",
    "webs.bldr.toolbar.text.36": "36",
    "webs.bldr.toolbar.text.3Sec": "3 Sec",
    "webs.bldr.toolbar.text.3Seconds": "3 Seconds",
    "webs.bldr.toolbar.text.4": "4",
    "webs.bldr.toolbar.text.4000": "4000",
    "webs.bldr.toolbar.text.48": "48",
    "webs.bldr.toolbar.text.4Sec": "4 Sec",
    "webs.bldr.toolbar.text.4Seconds": "4 Seconds",
    "webs.bldr.toolbar.text.5": "5",
    "webs.bldr.toolbar.text.5000": "5000",
    "webs.bldr.toolbar.text.5Sec": "5 Sec",
    "webs.bldr.toolbar.text.5Seconds": "5 Seconds",
    "webs.bldr.toolbar.text.6": "6",
    "webs.bldr.toolbar.text.6Sec": "6 Sec",
    "webs.bldr.toolbar.text.7": "7",
    "webs.bldr.toolbar.text.72": "72",
    "webs.bldr.toolbar.text.75%": "75%",
    "webs.bldr.toolbar.text.7Sec": "7 Sec",
    "webs.bldr.toolbar.text.8": "8",
    "webs.bldr.toolbar.text.80%": "80%",
    "webs.bldr.toolbar.text.85%": "85%",
    "webs.bldr.toolbar.text.9": "9",
    "webs.bldr.toolbar.text.90%": "90%",
    "webs.bldr.toolbar.text.95%": "95%",
    "webs.bldr.toolbar.text.A,B,C": "A, B, C...",
    "webs.bldr.toolbar.text.A,B,C¿": "A, B, C&hellip;",
    "webs.bldr.toolbar.text.Accept": "Accept",
    "webs.bldr.toolbar.text.Accessibility": "Accessibility",
    "webs.bldr.toolbar.text.Add": "Add",
    "webs.bldr.toolbar.text.AddImage": "Add Image",
    "webs.bldr.toolbar.text.AddText": "Add Text",
    "webs.bldr.toolbar.text.Address": "Address",
    "webs.bldr.toolbar.text.AddressBook": "Address Book",
    "webs.bldr.toolbar.text.AddressBookOpen": "Address Book Open",
    "webs.bldr.toolbar.text.Advanced": "Advanced",
    "webs.bldr.toolbar.text.AdvancedSettings": "Advanced Settings",
    "webs.bldr.toolbar.text.Agenda": "Agenda",
    "webs.bldr.toolbar.text.Airmail": "Airmail",
    "webs.bldr.toolbar.text.Airplane": "Airplane",
    "webs.bldr.toolbar.text.Alarm": "Alarm",
    "webs.bldr.toolbar.text.AlarmClock": "Alarm Clock",
    "webs.bldr.toolbar.text.Album": "Album",
    "webs.bldr.toolbar.text.Alert": "Alert",
    "webs.bldr.toolbar.text.AlignCenter": "Align Center",
    "webs.bldr.toolbar.text.AlignJustify": "Align Justify",
    "webs.bldr.toolbar.text.AlignLeft": "Align Left",
    "webs.bldr.toolbar.text.AlignRight": "Align Right",
    "webs.bldr.toolbar.text.AlternateRow": "Alternate&nbsp;Row",
    "webs.bldr.toolbar.text.Annoucement": "Annoucement",
    "webs.bldr.toolbar.text.Apple": "Apple",
    "webs.bldr.toolbar.text.ArrowDown": "Arrow Down",
    "webs.bldr.toolbar.text.ArrowLeft": "Arrow Left",
    "webs.bldr.toolbar.text.ArrowRight": "Arrow Right",
    "webs.bldr.toolbar.text.ArrowUp": "Arrow Up",
    "webs.bldr.toolbar.text.ArtBrush": "Art Brush",
    "webs.bldr.toolbar.text.Asterisk": "Asterisk",
    "webs.bldr.toolbar.text.AsteriskYellow": "Asterisk Yellow",
    "webs.bldr.toolbar.text.Attach": "Attach",
    "webs.bldr.toolbar.text.Attribution": "Attribution",
    "webs.bldr.toolbar.text.Auction": "Auction",
    "webs.bldr.toolbar.text.AuctionHammer": "Auction Hammer",
    "webs.bldr.toolbar.text.Autoplay": "Autoplay",
    "webs.bldr.toolbar.text.Award": "Award",
    "webs.bldr.toolbar.text.AwardStarBronze": "Award Star Bronze",
    "webs.bldr.toolbar.text.Background": "Background",
    "webs.bldr.toolbar.text.Balloon": "Balloon",
    "webs.bldr.toolbar.text.Baloon": "Baloon",
    "webs.bldr.toolbar.text.Bandaid": "Bandaid",
    "webs.bldr.toolbar.text.Barchart": "Barchart",
    "webs.bldr.toolbar.text.Basket": "Basket",
    "webs.bldr.toolbar.text.Basketball": "Basketball",
    "webs.bldr.toolbar.text.Beer": "Beer",
    "webs.bldr.toolbar.text.Bell": "Bell",
    "webs.bldr.toolbar.text.Bicycle": "Bicycle",
    "webs.bldr.toolbar.text.Binocular": "Binocular",
    "webs.bldr.toolbar.text.BlueFlag": "Blue Flag",
    "webs.bldr.toolbar.text.Bluetooth": "Bluetooth",
    "webs.bldr.toolbar.text.Boat": "Boat",
    "webs.bldr.toolbar.text.Bold": "Bold",
    "webs.bldr.toolbar.text.Book": "Book",
    "webs.bldr.toolbar.text.BookAddresses": "Book Addresses",
    "webs.bldr.toolbar.text.Bookmark": "Bookmark",
    "webs.bldr.toolbar.text.BookwithBookmark": "Book with Bookmark",
    "webs.bldr.toolbar.text.Boolean": "Boolean",
    "webs.bldr.toolbar.text.Border": "Border",
    "webs.bldr.toolbar.text.BorderColor": "Border Color",
    "webs.bldr.toolbar.text.Briefcase": "Briefcase",
    "webs.bldr.toolbar.text.Brightness": "Brightness",
    "webs.bldr.toolbar.text.Broom": "Broom",
    "webs.bldr.toolbar.text.Bug": "Bug",
    "webs.bldr.toolbar.text.Building": "Building",
    "webs.bldr.toolbar.text.BulletStar": "Bullet Star",
    "webs.bldr.toolbar.text.Burn": "Burn",
    "webs.bldr.toolbar.text.Bus": "Bus",
    "webs.bldr.toolbar.text.BusinessUser": "Business User",
    "webs.bldr.toolbar.text.Butterfly": "Butterfly",
    "webs.bldr.toolbar.text.ButtonColor": "Button Color",
    "webs.bldr.toolbar.text.ButtonSize": "Button Size",
    "webs.bldr.toolbar.text.CD": "CD",
    "webs.bldr.toolbar.text.Cake": "Cake",
    "webs.bldr.toolbar.text.Calculator": "Calculator",
    "webs.bldr.toolbar.text.Calendar": "Calendar",
    "webs.bldr.toolbar.text.Camera": "Camera",
    "webs.bldr.toolbar.text.Car": "Car",
    "webs.bldr.toolbar.text.Card": "Card",
    "webs.bldr.toolbar.text.CardCredit": "Card Credit",
    "webs.bldr.toolbar.text.CardDebit": "Card Debit",
    "webs.bldr.toolbar.text.CarouselSettings": "Carousel Settings",
    "webs.bldr.toolbar.text.Cart": "Cart",
    "webs.bldr.toolbar.text.Center": "Center",
    "webs.bldr.toolbar.text.ChangeBackground": "Change Background",
    "webs.bldr.toolbar.text.ChangeImage": "Change Image",
    "webs.bldr.toolbar.text.ChangeLogo": "Change Logo",
    "webs.bldr.toolbar.text.ChangeVideo": "Change Video",
    "webs.bldr.toolbar.text.Chart": "Chart",
    "webs.bldr.toolbar.text.ChartBar": "Chart Bar",
    "webs.bldr.toolbar.text.ChartCurve": "Chart Curve",
    "webs.bldr.toolbar.text.ChartPie": "Chart Pie",
    "webs.bldr.toolbar.text.ChartUp": "Chart Up",
    "webs.bldr.toolbar.text.Check": "Check",
    "webs.bldr.toolbar.text.CheckBox": "Check Box",
    "webs.bldr.toolbar.text.ChevronExpand": "Chevron Expand",
    "webs.bldr.toolbar.text.Clapperboard_Open": "Clapperboard_Open",
    "webs.bldr.toolbar.text.Classy": "Classy",
    "webs.bldr.toolbar.text.Clear": "Clear",
    "webs.bldr.toolbar.text.ClearFormatting": "Clear Formatting",
    "webs.bldr.toolbar.text.Clickonanelementtoshoweditoptions": "Click on an element to show edit options",
    "webs.bldr.toolbar.text.Clickonyourtexttoeditit": "Click on your text to edit it",
    "webs.bldr.toolbar.text.Clipboard": "Clipboard",
    "webs.bldr.toolbar.text.ClipboardText": "Clipboard Text",
    "webs.bldr.toolbar.text.Clock": "Clock",
    "webs.bldr.toolbar.text.CoffeeMug": "Coffee Mug",
    "webs.bldr.toolbar.text.Coins": "Coins",
    "webs.bldr.toolbar.text.Color": "Color",
    "webs.bldr.toolbar.text.ColorScheme": "Color Scheme",
    "webs.bldr.toolbar.text.Comment": "Comment",
    "webs.bldr.toolbar.text.Comments": "Comments",
    "webs.bldr.toolbar.text.Compact_Disc": "Compact_Disc",
    "webs.bldr.toolbar.text.Compass": "Compass",
    "webs.bldr.toolbar.text.Computer": "Computer",
    "webs.bldr.toolbar.text.Computer_Keyboard": "Computer_Keyboard",
    "webs.bldr.toolbar.text.ConnectionSignal": "Connection Signal",
    "webs.bldr.toolbar.text.Construction": "Construction",
    "webs.bldr.toolbar.text.ConstructionHat": "Construction Hat",
    "webs.bldr.toolbar.text.ContactBook": "Contact Book",
    "webs.bldr.toolbar.text.Contacts_Alt": "Contacts_Alt",
    "webs.bldr.toolbar.text.ControllerPlay": "Controller Play",
    "webs.bldr.toolbar.text.Cookie": "Cookie",
    "webs.bldr.toolbar.text.Cool": "Cool",
    "webs.bldr.toolbar.text.Cow": "Cow",
    "webs.bldr.toolbar.text.Cup": "Cup",
    "webs.bldr.toolbar.text.Cursor": "Cursor",
    "webs.bldr.toolbar.text.Cut": "Cut",
    "webs.bldr.toolbar.text.Cutlery": "Cutlery",
    "webs.bldr.toolbar.text.Dark": "Dark",
    "webs.bldr.toolbar.text.Dashboard": "Dashboard",
    "webs.bldr.toolbar.text.Date": "Date",
    "webs.bldr.toolbar.text.DecreaseFontSize": "Decrease Font Size",
    "webs.bldr.toolbar.text.Default": "Default",
    "webs.bldr.toolbar.text.Delete": "Delete",
    "webs.bldr.toolbar.text.DeleteSlide": "Delete Slide",
    "webs.bldr.toolbar.text.DeliveryTruck": "Delivery Truck",
    "webs.bldr.toolbar.text.DigitalCamcorder": "Digital Camcorder",
    "webs.bldr.toolbar.text.Direction_Board": "Direction_Board",
    "webs.bldr.toolbar.text.Disc": "Disc",
    "webs.bldr.toolbar.text.Discussion": "Discussion",
    "webs.bldr.toolbar.text.DividerColor": "Divider Color",
    "webs.bldr.toolbar.text.DividerStyles": "Divider Styles",
    "webs.bldr.toolbar.text.Document": "Document",
    "webs.bldr.toolbar.text.DocumentArrow": "Document Arrow",
    "webs.bldr.toolbar.text.DocumentEmpty": "Document Empty",
    "webs.bldr.toolbar.text.DocumentMusic": "Document Music",
    "webs.bldr.toolbar.text.DocumentText": "Document Text",
    "webs.bldr.toolbar.text.Done": "Done",
    "webs.bldr.toolbar.text.Done_Square": "Done_Square",
    "webs.bldr.toolbar.text.Door": "Door",
    "webs.bldr.toolbar.text.DoubleContrast": "Double Contrast",
    "webs.bldr.toolbar.text.Down": "Down",
    "webs.bldr.toolbar.text.Download": "Download",
    "webs.bldr.toolbar.text.Drink": "Drink",
    "webs.bldr.toolbar.text.Earth": "Earth",
    "webs.bldr.toolbar.text.EditButton": "Edit Button",
    "webs.bldr.toolbar.text.EditForm": "Edit Form",
    "webs.bldr.toolbar.text.EditHTML": "Edit HTML",
    "webs.bldr.toolbar.text.EditParagraph": "Edit Paragraph",
    "webs.bldr.toolbar.text.EditWidget": "Edit Widget",
    "webs.bldr.toolbar.text.Edit_Button": "Edit Button",
    "webs.bldr.toolbar.text.Eight-ball": "Eight-ball",
    "webs.bldr.toolbar.text.Email": "Email",
    "webs.bldr.toolbar.text.EmotionSmile": "Emotion Smile",
    "webs.bldr.toolbar.text.EnteryourURL...": "Enter your URL...",
    "webs.bldr.toolbar.text.Enteryouraddress...": "Enter your address...",
    "webs.bldr.toolbar.text.Enteryourusername...": "Enter your username...",
    "webs.bldr.toolbar.text.Envelope": "Envelope",
    "webs.bldr.toolbar.text.Eye": "Eye",
    "webs.bldr.toolbar.text.FacebookURL": "Facebook URL",
    "webs.bldr.toolbar.text.Fade": "Fade",
    "webs.bldr.toolbar.text.Fan": "Fan",
    "webs.bldr.toolbar.text.Fatcow": "Fatcow",
    "webs.bldr.toolbar.text.Favorite": "Favorite",
    "webs.bldr.toolbar.text.Feed": "Feed",
    "webs.bldr.toolbar.text.FeverChart": "Fever Chart",
    "webs.bldr.toolbar.text.Film": "Film",
    "webs.bldr.toolbar.text.Financial": "Financial",
    "webs.bldr.toolbar.text.Fire": "Fire",
    "webs.bldr.toolbar.text.FirstAidBox": "First Aid Box",
    "webs.bldr.toolbar.text.Flag": "Flag",
    "webs.bldr.toolbar.text.Flash": "Flash",
    "webs.bldr.toolbar.text.Folder": "Folder",
    "webs.bldr.toolbar.text.FolderEmpty": "Folder Empty",
    "webs.bldr.toolbar.text.FolderHorizontal": "Folder Horizontal",
    "webs.bldr.toolbar.text.FollowerCount": "Follower Count",
    "webs.bldr.toolbar.text.Football": "Football",
    "webs.bldr.toolbar.text.Frame": "Frame",
    "webs.bldr.toolbar.text.FramePicker": "Frame Picker",
    "webs.bldr.toolbar.text.Fruit": "Fruit",
    "webs.bldr.toolbar.text.Fugue": "Fugue",
    "webs.bldr.toolbar.text.GallerySettings": "Gallery Settings",
    "webs.bldr.toolbar.text.GameController": "Game Controller",
    "webs.bldr.toolbar.text.Get&nbsp;Directions": "Get&nbsp;Directions",
    "webs.bldr.toolbar.text.GetDirections": "Get Directions",
    "webs.bldr.toolbar.text.Gift": "Gift",
    "webs.bldr.toolbar.text.Globe": "Globe",
    "webs.bldr.toolbar.text.Go-toBottom": "Go-to Bottom",
    "webs.bldr.toolbar.text.Go-toTop": "Go-to Top",
    "webs.bldr.toolbar.text.GoldMedal": "Gold Medal",
    "webs.bldr.toolbar.text.Golf": "Golf",
    "webs.bldr.toolbar.text.Guitar": "Guitar",
    "webs.bldr.toolbar.text.Gym": "Gym",
    "webs.bldr.toolbar.text.HCarousel": "H Carousel",
    "webs.bldr.toolbar.text.HSlide": "H Slide",
    "webs.bldr.toolbar.text.Hammer": "Hammer",
    "webs.bldr.toolbar.text.Hand": "Hand",
    "webs.bldr.toolbar.text.Hand-pointer": "Hand-pointer",
    "webs.bldr.toolbar.text.Handshake": "Handshake",
    "webs.bldr.toolbar.text.Header": "Header",
    "webs.bldr.toolbar.text.HeaderColor": "Header&nbsp;Color",
    "webs.bldr.toolbar.text.HeaderGrid": "Header Grid",
    "webs.bldr.toolbar.text.HeaderSettings": "Header Settings",
    "webs.bldr.toolbar.text.Headphone": "Headphone",
    "webs.bldr.toolbar.text.Headphones": "Headphones",
    "webs.bldr.toolbar.text.Heart": "Heart",
    "webs.bldr.toolbar.text.Help": "Help",
    "webs.bldr.toolbar.text.Help_Circle": "Help_Circle",
    "webs.bldr.toolbar.text.Highlighter": "Highlighter",
    "webs.bldr.toolbar.text.Home": "Home",
    "webs.bldr.toolbar.text.Hot": "Hot",
    "webs.bldr.toolbar.text.Hourglass": "Hourglass",
    "webs.bldr.toolbar.text.I,II,III": "I, II, III...",
    "webs.bldr.toolbar.text.I,II,III&hellip;": "I, II, III&hellip;",
    "webs.bldr.toolbar.text.Icon": "Icon",
    "webs.bldr.toolbar.text.IconPicker": "Icon Picker",
    "webs.bldr.toolbar.text.IconStyles": "Icon Styles",
    "webs.bldr.toolbar.text.Image": "Image",
    "webs.bldr.toolbar.text.ImageBMP": "Image BMP",
    "webs.bldr.toolbar.text.ImageJPG": "Image JPG",
    "webs.bldr.toolbar.text.Images": "Images",
    "webs.bldr.toolbar.text.Images_Night_Scene": "Images_Night_Scene",
    "webs.bldr.toolbar.text.IncreaseFontSize": "Increase Font Size",
    "webs.bldr.toolbar.text.Indent": "Indent",
    "webs.bldr.toolbar.text.Infinite": "Infinite",
    "webs.bldr.toolbar.text.Info": "Info",
    "webs.bldr.toolbar.text.Information": "Information",
    "webs.bldr.toolbar.text.InnerOpacityDark": "Inner Opacity Dark",
    "webs.bldr.toolbar.text.InnerOpacityLight": "Inner Opacity Light",
    "webs.bldr.toolbar.text.Iphone": "Iphone",
    "webs.bldr.toolbar.text.Ipod": "Ipod",
    "webs.bldr.toolbar.text.Italic": "Italic",
    "webs.bldr.toolbar.text.Key": "Key",
    "webs.bldr.toolbar.text.Lab": "Lab",
    "webs.bldr.toolbar.text.Laptop": "Laptop",
    "webs.bldr.toolbar.text.Large": "Large",
    "webs.bldr.toolbar.text.LargeIcons": "Large Icons",
    "webs.bldr.toolbar.text.LayerDown": "Layer Down",
    "webs.bldr.toolbar.text.LayerUp": "Layer Up",
    "webs.bldr.toolbar.text.Leaf": "Leaf",
    "webs.bldr.toolbar.text.Left": "Left",
    "webs.bldr.toolbar.text.Lifebuoy": "Lifebuoy",
    "webs.bldr.toolbar.text.Light": "Light",
    "webs.bldr.toolbar.text.Light-bulb": "Light-bulb",
    "webs.bldr.toolbar.text.Lightning": "Lightning",
    "webs.bldr.toolbar.text.Link": "Link",
    "webs.bldr.toolbar.text.LinkColor": "Link Color",
    "webs.bldr.toolbar.text.List": "List",
    "webs.bldr.toolbar.text.Location": "Location",
    "webs.bldr.toolbar.text.Lock": "Lock",
    "webs.bldr.toolbar.text.Login": "Login",
    "webs.bldr.toolbar.text.Logo": "Logo",
    "webs.bldr.toolbar.text.Logout": "Logout",
    "webs.bldr.toolbar.text.Luggage": "Luggage",
    "webs.bldr.toolbar.text.MagicWand": "Magic Wand",
    "webs.bldr.toolbar.text.Magnifier": "Magnifier",
    "webs.bldr.toolbar.text.Mail": "Mail",
    "webs.bldr.toolbar.text.ManageSlideshow": "Manage Slideshow",
    "webs.bldr.toolbar.text.ManageSocial": "Manage Social",
    "webs.bldr.toolbar.text.Manual": "Manual",
    "webs.bldr.toolbar.text.Margin": "Margin",
    "webs.bldr.toolbar.text.Marker": "Marker",
    "webs.bldr.toolbar.text.MartiniGlass": "Martini Glass",
    "webs.bldr.toolbar.text.Medal": "Medal",
    "webs.bldr.toolbar.text.Medium": "Medium",
    "webs.bldr.toolbar.text.Microphone": "Microphone",
    "webs.bldr.toolbar.text.MobilePhone": "Mobile Phone",
    "webs.bldr.toolbar.text.Money": "Money",
    "webs.bldr.toolbar.text.MoneyCoin": "Money Coin",
    "webs.bldr.toolbar.text.MoneyDollar": "Money Dollar",
    "webs.bldr.toolbar.text.Monitor": "Monitor",
    "webs.bldr.toolbar.text.Monitor_Off": "Monitor_Off",
    "webs.bldr.toolbar.text.Museum": "Museum",
    "webs.bldr.toolbar.text.Music": "Music",
    "webs.bldr.toolbar.text.NewMail": "New Mail",
    "webs.bldr.toolbar.text.Newspaper": "Newspaper",
    "webs.bldr.toolbar.text.Next": "Next",
    "webs.bldr.toolbar.text.None": "None",
    "webs.bldr.toolbar.text.Note": "Note",
    "webs.bldr.toolbar.text.Notebook": "Notebook",
    "webs.bldr.toolbar.text.Notepad": "Notepad",
    "webs.bldr.toolbar.text.Numbers": "Numbers",
    "webs.bldr.toolbar.text.OK": "OK",
    "webs.bldr.toolbar.text.Off": "Off",
    "webs.bldr.toolbar.text.Options": "Options",
    "webs.bldr.toolbar.text.Orbit": "Orbit",
    "webs.bldr.toolbar.text.Outdent": "Outdent",
    "webs.bldr.toolbar.text.Page": "Page",
    "webs.bldr.toolbar.text.PageBlank": "Page Blank",
    "webs.bldr.toolbar.text.PaintBrush": "Paint Brush",
    "webs.bldr.toolbar.text.Paper": "Paper",
    "webs.bldr.toolbar.text.PaperClip": "Paper Clip",
    "webs.bldr.toolbar.text.Paperclip": "Paperclip",
    "webs.bldr.toolbar.text.Paypal": "Paypal",
    "webs.bldr.toolbar.text.Pencil": "Pencil",
    "webs.bldr.toolbar.text.Phone": "Phone",
    "webs.bldr.toolbar.text.PhoneClassic": "Phone Classic",
    "webs.bldr.toolbar.text.Picture": "Picture",
    "webs.bldr.toolbar.text.Pin": "Pin",
    "webs.bldr.toolbar.text.Plus": "Plus",
    "webs.bldr.toolbar.text.Popcorn": "Popcorn",
    "webs.bldr.toolbar.text.Position": "Position",
    "webs.bldr.toolbar.text.Power": "Power",
    "webs.bldr.toolbar.text.Previous": "Previous",
    "webs.bldr.toolbar.text.PriceTag": "Price Tag",
    "webs.bldr.toolbar.text.Print": "Print",
    "webs.bldr.toolbar.text.Process": "Process",
    "webs.bldr.toolbar.text.ProductSettings": "Product Settings",
    "webs.bldr.toolbar.text.Puff": "Puff",
    "webs.bldr.toolbar.text.Question": "Question",
    "webs.bldr.toolbar.text.RSS": "RSS",
    "webs.bldr.toolbar.text.Rainbow": "Rainbow",
    "webs.bldr.toolbar.text.Raquet": "Raquet",
    "webs.bldr.toolbar.text.Rectangle": "Landscape",
    "webs.bldr.toolbar.text.Recycle": "Recycle",
    "webs.bldr.toolbar.text.RemoveFrame": "Remove Frame",
    "webs.bldr.toolbar.text.RemoveIcon": "Remove Icon",
    "webs.bldr.toolbar.text.RemoveLink": "Remove Link",
    "webs.bldr.toolbar.text.Report": "Report",
    "webs.bldr.toolbar.text.ReportPaper": "Report Paper",
    "webs.bldr.toolbar.text.Restrict": "Restrict",
    "webs.bldr.toolbar.text.Ribbon": "Ribbon",
    "webs.bldr.toolbar.text.Right": "Right",
    "webs.bldr.toolbar.text.Rocket": "Rocket",
    "webs.bldr.toolbar.text.Rocky": "Rocky",
    "webs.bldr.toolbar.text.RowColor": "Row&nbsp;Color",
    "webs.bldr.toolbar.text.Rss": "Rss",
    "webs.bldr.toolbar.text.Ruby": "Ruby",
    "webs.bldr.toolbar.text.Satellite": "Satellite",
    "webs.bldr.toolbar.text.Save": "Save",
    "webs.bldr.toolbar.text.Scheme": "Scheme",
    "webs.bldr.toolbar.text.Scull": "Scull",
    "webs.bldr.toolbar.text.Search": "Search",
    "webs.bldr.toolbar.text.Setting": "Setting",
    "webs.bldr.toolbar.text.Settings": "Settings",
    "webs.bldr.toolbar.text.Share": "Share",
    "webs.bldr.toolbar.text.Shield": "Shield",
    "webs.bldr.toolbar.text.ShoppingBag": "Shopping Bag",
    "webs.bldr.toolbar.text.ShoppingBasket": "Shopping Basket",
    "webs.bldr.toolbar.text.ShoppingCart": "Shopping Cart",
    "webs.bldr.toolbar.text.Shovel": "Shovel",
    "webs.bldr.toolbar.text.Show&nbsp;Controls": "Show&nbsp;Controls",
    "webs.bldr.toolbar.text.Show&nbsp;Email": "Show&nbsp;Email",
    "webs.bldr.toolbar.text.Show&nbsp;Faces": "Show Faces",
    "webs.bldr.toolbar.text.Show&nbsp;Google&nbsp;Plus": "Show&nbsp;Google&nbsp;Plus",
    "webs.bldr.toolbar.text.Show&nbsp;Header": "Show Header",
    "webs.bldr.toolbar.text.Show&nbsp;Like": "Show&nbsp;Like",
    "webs.bldr.toolbar.text.Show&nbsp;Marker": "Show Marker",
    "webs.bldr.toolbar.text.Show&nbsp;More": "Show&nbsp;More",
    "webs.bldr.toolbar.text.Show&nbsp;Stream": "Show Stream",
    "webs.bldr.toolbar.text.Show&nbsp;Tweet": "Show&nbsp;Tweet",
    "webs.bldr.toolbar.text.ShowControls": "Show Controls",
    "webs.bldr.toolbar.text.ShowEmail": "Show Email",
    "webs.bldr.toolbar.text.ShowFaces": "Show&nbsp;Faces",
    "webs.bldr.toolbar.text.ShowGooglePlus": "Show Google Plus",
    "webs.bldr.toolbar.text.ShowHeader": "Show&nbsp;Header",
    "webs.bldr.toolbar.text.ShowLike": "Show Like",
    "webs.bldr.toolbar.text.ShowMarker": "Show Marker",
    "webs.bldr.toolbar.text.ShowMore": "Show More",
    "webs.bldr.toolbar.text.ShowStream": "Show&nbsp;Stream",
    "webs.bldr.toolbar.text.ShowTweet": "Show Tweet",
    "webs.bldr.toolbar.text.Shownull;Header": "Show Header",
    "webs.bldr.toolbar.text.Size": "Size",
    "webs.bldr.toolbar.text.SlideshowSettings": "Slideshow Settings",
    "webs.bldr.toolbar.text.Small": "Small",
    "webs.bldr.toolbar.text.SmallIcons": "Small Icons",
    "webs.bldr.toolbar.text.Smiley": "Smiley",
    "webs.bldr.toolbar.text.Soccer": "Soccer",
    "webs.bldr.toolbar.text.Soccer_Ball": "Soccer_Ball",
    "webs.bldr.toolbar.text.SocialIconStyles": "Social Icon Styles",
    "webs.bldr.toolbar.text.Speaker": "Speaker",
    "webs.bldr.toolbar.text.Speed": "Speed",
    "webs.bldr.toolbar.text.Square": "Square",
    "webs.bldr.toolbar.text.Star": "Star",
    "webs.bldr.toolbar.text.StickyNote": "Sticky Note",
    "webs.bldr.toolbar.text.StockChart": "Stock Chart",
    "webs.bldr.toolbar.text.Stop": "Stop",
    "webs.bldr.toolbar.text.Strikethrough": "Strikethrough",
    "webs.bldr.toolbar.text.Style": "Style",
    "webs.bldr.toolbar.text.Styles": "Styles",
    "webs.bldr.toolbar.text.T-shirt": "T-shirt",
    "webs.bldr.toolbar.text.TableSettings": "Table Settings",
    "webs.bldr.toolbar.text.Tag": "Tag",
    "webs.bldr.toolbar.text.TagCloud": "Tag Cloud",
    "webs.bldr.toolbar.text.Tagline": "Tagline",
    "webs.bldr.toolbar.text.Tape": "Tape",
    "webs.bldr.toolbar.text.Tennis": "Tennis",
    "webs.bldr.toolbar.text.Text": "Text",
    "webs.bldr.toolbar.text.TextColor": "Text Color",
    "webs.bldr.toolbar.text.ThismoduleisdefinedbyZIN": "This module is defined by ZIN",
    "webs.bldr.toolbar.text.ThumbDown": "Thumb Down",
    "webs.bldr.toolbar.text.ThumbUp": "Thumb Up",
    "webs.bldr.toolbar.text.ThumbnailsBottom": "Thumbnails Bottom",
    "webs.bldr.toolbar.text.ThumbnailsNone": "Thumbnails None",
    "webs.bldr.toolbar.text.ThumbnailsTop": "Thumbnails Top",
    "webs.bldr.toolbar.text.Tick": "Tick",
    "webs.bldr.toolbar.text.Ticket_Golden": "Ticket_Golden",
    "webs.bldr.toolbar.text.Ticket_Red": "Ticket_Red",
    "webs.bldr.toolbar.text.Title": "Title",
    "webs.bldr.toolbar.text.ToggleGrid": "Toggle Grid",
    "webs.bldr.toolbar.text.Tool": "Tool",
    "webs.bldr.toolbar.text.Transition": "Transition",
    "webs.bldr.toolbar.text.Tree": "Tree",
    "webs.bldr.toolbar.text.Trophy": "Trophy",
    "webs.bldr.toolbar.text.Tv": "Tv",
    "webs.bldr.toolbar.text.TwitterUsername": "Twitter Username",
    "webs.bldr.toolbar.text.UShadow": "U Shadow",
    "webs.bldr.toolbar.text.Umbella": "Umbella",
    "webs.bldr.toolbar.text.Underline": "Underline",
    "webs.bldr.toolbar.text.Undo": "Undo",
    "webs.bldr.toolbar.text.Unlock": "Unlock",
    "webs.bldr.toolbar.text.Up": "Up",
    "webs.bldr.toolbar.text.Upload": "Upload",
    "webs.bldr.toolbar.text.UploadAudio": "Upload Audio",
    "webs.bldr.toolbar.text.Usb": "Usb",
    "webs.bldr.toolbar.text.User": "User",
    "webs.bldr.toolbar.text.UserBlack": "User Black",
    "webs.bldr.toolbar.text.UserFemale": "User Female",
    "webs.bldr.toolbar.text.UserGray": "User Gray",
    "webs.bldr.toolbar.text.UserGreen": "User Green",
    "webs.bldr.toolbar.text.UserGroup": "User Group",
    "webs.bldr.toolbar.text.UserRed": "User Red",
    "webs.bldr.toolbar.text.UserSilhouette": "User Silhouette",
    "webs.bldr.toolbar.text.UserSuit": "User Suit",
    "webs.bldr.toolbar.text.Users": "Users",
    "webs.bldr.toolbar.text.VCarousel": "V Carousel",
    "webs.bldr.toolbar.text.VSlide": "V Slide",
    "webs.bldr.toolbar.text.VideoCamera": "Video Camera",
    "webs.bldr.toolbar.text.VideoClapper": "Video Clapper",
    "webs.bldr.toolbar.text.VideoReel": "Video Reel",
    "webs.bldr.toolbar.text.Videos": "Videos",
    "webs.bldr.toolbar.text.Walk": "Walk",
    "webs.bldr.toolbar.text.Weather": "Weather",
    "webs.bldr.toolbar.text.Web": "Web",
    "webs.bldr.toolbar.text.Webcam": "Webcam",
    "webs.bldr.toolbar.text.WhitePage": "White Page",
    "webs.bldr.toolbar.text.White_Lego": "White_Lego",
    "webs.bldr.toolbar.text.Width": "Width",
    "webs.bldr.toolbar.text.WineGlass": "Wine Glass",
    "webs.bldr.toolbar.text.Wireless": "Wireless",
    "webs.bldr.toolbar.text.Wrench": "Wrench",
    "webs.bldr.toolbar.text.ZoomIn": "Zoom In",
    "webs.bldr.toolbar.text.a,b,c": "<span style='text-transform:none;'>a, b, c...<\/span>",
    "webs.bldr.toolbar.text.a,b,c&hellip;": "<span style='text-transform:none;'>a, b, c...<\/span>",
    "webs.bldr.toolbar.text.addColumn": "+ Column",
    "webs.bldr.toolbar.text.addRow": "+ Row",
    "webs.bldr.toolbar.text.advanced_settings": "Advanced Settings",
    "webs.bldr.toolbar.text.align_center": "Align Center",
    "webs.bldr.toolbar.text.align_justify": "Align Justify",
    "webs.bldr.toolbar.text.align_left": "Align Left",
    "webs.bldr.toolbar.text.align_right": "Align Right",
    "webs.bldr.toolbar.text.alternateRow": "Alternate Row",
    "webs.bldr.toolbar.text.border": "Border",
    "webs.bldr.toolbar.text.borderColor": "Border Color",
    "webs.bldr.toolbar.text.both": "On Both Views",
    "webs.bldr.toolbar.text.bullet.decimal": "1, 2, 3...",
    "webs.bldr.toolbar.text.bullet.lowerAlpha": "a, b, c...",
    "webs.bldr.toolbar.text.bullet.lowerRoman": "i, ii, iii...",
    "webs.bldr.toolbar.text.bullet.upperAlpha": "A, B, C...",
    "webs.bldr.toolbar.text.bullet.upperRoman": "I, II, III...",
    "webs.bldr.toolbar.text.button_color": "Button Color",
    "webs.bldr.toolbar.text.buttons": "Buttons",
    "webs.bldr.toolbar.text.carouselHorizontal": "carouselHorizontal",
    "webs.bldr.toolbar.text.carouselVertical": "carouselVertical",
    "webs.bldr.toolbar.text.center": "center",
    "webs.bldr.toolbar.text.change_image": "Change Image",
    "webs.bldr.toolbar.text.clapperboard_open": "Clapperboard_Open",
    "webs.bldr.toolbar.text.clear_formatting": "Clear Formatting",
    "webs.bldr.toolbar.text.crop-style-portrait": "Portrait",
    "webs.bldr.toolbar.text.crop-style-rectangle": "Landscape",
    "webs.bldr.toolbar.text.crop-style-square": "Square",
    "webs.bldr.toolbar.text.crop-style-widescreen": "Widescreen",
    "webs.bldr.toolbar.text.custom": "Custom",
    "webs.bldr.toolbar.text.dark": "dark",
    "webs.bldr.toolbar.text.decimal": "1, 2, 3...",
    "webs.bldr.toolbar.text.decrease_font_size": "Decrease Font Size",
    "webs.bldr.toolbar.text.fade": "fade",
    "webs.bldr.toolbar.text.fbLikeHelpTip": "Enter your Facebook URL above",
    "webs.bldr.toolbar.text.fontSize.10": "10",
    "webs.bldr.toolbar.text.fontSize.11": "11",
    "webs.bldr.toolbar.text.fontSize.12": "12",
    "webs.bldr.toolbar.text.fontSize.14": "14",
    "webs.bldr.toolbar.text.fontSize.16": "16",
    "webs.bldr.toolbar.text.fontSize.18": "18",
    "webs.bldr.toolbar.text.fontSize.20": "20",
    "webs.bldr.toolbar.text.fontSize.22": "22",
    "webs.bldr.toolbar.text.fontSize.24": "24",
    "webs.bldr.toolbar.text.fontSize.26": "26",
    "webs.bldr.toolbar.text.fontSize.28": "28",
    "webs.bldr.toolbar.text.fontSize.36": "36",
    "webs.bldr.toolbar.text.fontSize.48": "48",
    "webs.bldr.toolbar.text.fontSize.72": "72",
    "webs.bldr.toolbar.text.fontSize.8": "8",
    "webs.bldr.toolbar.text.fontSize.9": "9",
    "webs.bldr.toolbar.text.framePicker": "Frame Picker",
    "webs.bldr.toolbar.text.grid": "On Grid View Only",
    "webs.bldr.toolbar.text.header": "Header",
    "webs.bldr.toolbar.text.headerColor": "Header Color",
    "webs.bldr.toolbar.text.hover-effect-color-black": "Dark",
    "webs.bldr.toolbar.text.hover-effect-color-white": "Light",
    "webs.bldr.toolbar.text.hover-effect-none": "None",
    "webs.bldr.toolbar.text.hover-effect-plusSign": "Plus",
    "webs.bldr.toolbar.text.hover-effect-titleSign": "Title",
    "webs.bldr.toolbar.text.hover-effect-viewSign": "Button",
    "webs.bldr.toolbar.text.hover-effect-zoomSign": "Magnify",
    "webs.bldr.toolbar.text.i,ii,iii": "<span style='text-transform:none;'>i, ii, iii...<\/span>",
    "webs.bldr.toolbar.text.i,ii,iii&hellip;": "<span style='text-transform:none;'>i, ii, iii&hellip;<\/span>",
    "webs.bldr.toolbar.text.iconPicker": "Icon Picker",
    "webs.bldr.toolbar.text.increase_font_size": "Increase Font Size",
    "webs.bldr.toolbar.text.large": "large",
    "webs.bldr.toolbar.text.largeIcons": "Large Icons",
    "webs.bldr.toolbar.text.left": "left",
    "webs.bldr.toolbar.text.light": "light",
    "webs.bldr.toolbar.text.lightbox": "On Lightbox Only",
    "webs.bldr.toolbar.text.lowerAlpha": "a, b, c...",
    "webs.bldr.toolbar.text.lowerRoman": "i, ii, iii...",
    "webs.bldr.toolbar.text.medium": "medium",
    "webs.bldr.toolbar.text.never": "Never",
    "webs.bldr.toolbar.text.none": "none",
    "webs.bldr.toolbar.text.padding-large": "Large",
    "webs.bldr.toolbar.text.padding-medium": "Medium",
    "webs.bldr.toolbar.text.padding-none": "None",
    "webs.bldr.toolbar.text.padding-small": "Small",
    "webs.bldr.toolbar.text.photo_gallery.Grid": "Grid",
    "webs.bldr.toolbar.text.photo_gallery.Slideshow": "Slideshow",
    "webs.bldr.toolbar.text.photo_gallery.buttonStyle": "Button Style",
    "webs.bldr.toolbar.text.photo_gallery.caption": "Caption",
    "webs.bldr.toolbar.text.photo_gallery.color": "Hover Color",
    "webs.bldr.toolbar.text.photo_gallery.cropStyle": "Crop Style",
    "webs.bldr.toolbar.text.photo_gallery.cropStylePortrait": "Portrait",
    "webs.bldr.toolbar.text.photo_gallery.cropStyleRectangle": "Landscape",
    "webs.bldr.toolbar.text.photo_gallery.cropStyleSlideshow": "Crop Style",
    "webs.bldr.toolbar.text.photo_gallery.cropStyleSquare": "Square",
    "webs.bldr.toolbar.text.photo_gallery.gallerySettings": "Gallery Settings",
    "webs.bldr.toolbar.text.photo_gallery.gridPadding": "Grid Padding",
    "webs.bldr.toolbar.text.photo_gallery.hoverEffect": "Hover Icon",
    "webs.bldr.toolbar.text.photo_gallery.hoverEffect.none": "None",
    "webs.bldr.toolbar.text.photo_gallery.hoverEffect.plusSign": "Plus",
    "webs.bldr.toolbar.text.photo_gallery.hoverEffect.titleSign": "Title",
    "webs.bldr.toolbar.text.photo_gallery.hoverEffect.viewSign": "Button",
    "webs.bldr.toolbar.text.photo_gallery.hoverEffect.zoomSign": "Magnify",
    "webs.bldr.toolbar.text.photo_gallery.hoverEffectColor.black": "Dark",
    "webs.bldr.toolbar.text.photo_gallery.hoverEffectColor.white": "Light",
    "webs.bldr.toolbar.text.photo_gallery.lightbox": "Lightbox",
    "webs.bldr.toolbar.text.photo_gallery.lightboxToolTip": "",
    "webs.bldr.toolbar.text.photo_gallery.lightboxTooltip": "This will allow visitors to click on your gallery images and view them as a full-screen slideshow. ",
    "webs.bldr.toolbar.text.photo_gallery.manageImages": "Manage Images",
    "webs.bldr.toolbar.text.photo_gallery.paddingLarge": "Large",
    "webs.bldr.toolbar.text.photo_gallery.paddingMedium": "Medium",
    "webs.bldr.toolbar.text.photo_gallery.paddingNone": "None",
    "webs.bldr.toolbar.text.photo_gallery.paddingSmall": "Small",
    "webs.bldr.toolbar.text.photo_gallery.photosPerRow": "Photos Per Row",
    "webs.bldr.toolbar.text.photo_gallery.settings": "Settings",
    "webs.bldr.toolbar.text.photo_gallery.slideshowSettings": "Slideshow Settings",
    "webs.bldr.toolbar.text.photo_gallery.title": "Title",
    "webs.bldr.toolbar.text.photo_gallery.titlecaption.bothViews": "On Both Views",
    "webs.bldr.toolbar.text.photo_gallery.titlecaption.gridOnly": "On Grid View Only",
    "webs.bldr.toolbar.text.photo_gallery.titlecaption.lightboxOnly": "On Lightbox Only",
    "webs.bldr.toolbar.text.photo_gallery.titlecaption.never": "Never",
    "webs.bldr.toolbar.text.photo_gallery.type.grid": "Grid",
    "webs.bldr.toolbar.text.photo_gallery.viewType": "View Type",
    "webs.bldr.toolbar.text.photo_gallery_slideshow.buttonStyle": "Button Style",
    "webs.bldr.toolbar.text.photo_gallery_slideshow.buttonStyle1": "Anchored",
    "webs.bldr.toolbar.text.photo_gallery_slideshow.buttonStyle2": "Corner",
    "webs.bldr.toolbar.text.photo_gallery_slideshow.buttonStyle3": "Circle",
    "webs.bldr.toolbar.text.photo_gallery_slideshow.buttonStyle4": "Ellipsoid",
    "webs.bldr.toolbar.text.photo_gallery_slideshow.buttonStyle5": "No-Fill",
    "webs.bldr.toolbar.text.photo_gallery_slideshow.buttonStyle6": "Full Height",
    "webs.bldr.toolbar.text.photo_gallery_slideshow.cropStylePortrait": "Portrait",
    "webs.bldr.toolbar.text.photo_gallery_slideshow.cropStyleRectangle": "Rectangle",
    "webs.bldr.toolbar.text.photo_gallery_slideshow.cropStyleSquare": "Square",
    "webs.bldr.toolbar.text.photo_gallery_slideshow.cropStyleWidescreen": "Widescreen",
    "webs.bldr.toolbar.text.photo_gallery_slideshow.manageImages": "Manage Images",
    "webs.bldr.toolbar.text.photo_gallery_slideshow.settings": "Settings",
    "webs.bldr.toolbar.text.placeholderAddress": "Enter your address...",
    "webs.bldr.toolbar.text.placeholderUrl": "Enter your URL...",
    "webs.bldr.toolbar.text.placeholderUsername": "Enter your username...",
    "webs.bldr.toolbar.text.popular": "Popular",
    "webs.bldr.toolbar.text.puff": "puff",
    "webs.bldr.toolbar.text.recentcolors": "Recent Colors",
    "webs.bldr.toolbar.text.reset": "Reset",
    "webs.bldr.toolbar.text.right": "right",
    "webs.bldr.toolbar.text.rowColor": "Row Color",
    "webs.bldr.toolbar.text.slide-default": "None",
    "webs.bldr.toolbar.text.slide-fade": "Fade",
    "webs.bldr.toolbar.text.slideHorizontal": "slideHorizontal",
    "webs.bldr.toolbar.text.slideVertical": "slideVertical",
    "webs.bldr.toolbar.text.small": "small",
    "webs.bldr.toolbar.text.smallIcons": "Small Icons",
    "webs.bldr.toolbar.text.style1": "Anchored",
    "webs.bldr.toolbar.text.style2": "Corner",
    "webs.bldr.toolbar.text.style3": "Circle",
    "webs.bldr.toolbar.text.style4": "Ellipsoid",
    "webs.bldr.toolbar.text.style5": "No-Fill",
    "webs.bldr.toolbar.text.style6": "Full Height",
    "webs.bldr.toolbar.text.text_color": "Text Color",
    "webs.bldr.toolbar.text.thumbnail-bottom": "Bottom",
    "webs.bldr.toolbar.text.thumbnail-horizontalthumbnail-bottom": "Bottom",
    "webs.bldr.toolbar.text.thumbnail-horizontalthumbnail-top": "Top",
    "webs.bldr.toolbar.text.thumbnail-left": "Left",
    "webs.bldr.toolbar.text.thumbnail-none": "None",
    "webs.bldr.toolbar.text.thumbnail-right": "Right",
    "webs.bldr.toolbar.text.thumbnail-top": "Top",
    "webs.bldr.toolbar.text.thumbnail-verticalthumbnail-left": "Left",
    "webs.bldr.toolbar.text.thumbnail-verticalthumbnail-right": "Right",
    "webs.bldr.toolbar.text.thumbnailPosition": "Thumbnail Position",
    "webs.bldr.toolbar.text.twitterHelpTip": "Enter your Twitter username above",
    "webs.bldr.toolbar.text.upload_audio": "Upload Audio",
    "webs.bldr.toolbar.text.upperAlpha": "A, B, C...",
    "webs.bldr.toolbar.text.upperRoman": "I, II, III...",
    "webs.bldr.toolbar.text.webstore_products.manageProducts": "Manage Products",
    "webs.bldr.toolbar.text.webstore_products.name": "Show Name",
    "webs.bldr.toolbar.text.webstore_products.nameTooltip": "Show Product Name",
    "webs.bldr.toolbar.text.webstore_products.price": "Show Price",
    "webs.bldr.toolbar.text.webstore_products.productsPerRow": "Products Per Row",
    "webs.bldr.toolbar.text.webstore_products.settings": "Settings",
    "webs.bldr.toolbar.text.webstore_products.viewProductBtn": "Show Button"
});
