define({
    "webs.appStore.agreePrompt": "By installing you indicate that you have read and agree to this app's",
    "webs.appStore.appsio": "Listings",
    "webs.appStore.arcade": "Arcade",
    "webs.appStore.arcadedev": "Arcade",
    "webs.appStore.auth": "Sign In",
    "webs.appStore.authbeta": "authbeta app",
    "webs.appStore.authdom": "authdom",
    "webs.appStore.authjlin": "authjlin",
    "webs.appStore.authlocal": "Sign In",
    "webs.appStore.authmark": "authdom",
    "webs.appStore.authprod": "Auth Prod",
    "webs.appStore.authseon": "authseon app",
    "webs.appStore.badges": "badges_live",
    "webs.appStore.badges1_dev": "badges1_dev",
    "webs.appStore.badges2_dev": "badges2_dev",
    "webs.appStore.badges3_dev": "badges3_dev",
    "webs.appStore.badges_test": "badges_test",
    "webs.appStore.blog": "Blog",
    "webs.appStore.blogbeta": "blogsbeta",
    "webs.appStore.blogdev": "notusedbutidrissaystoadditback",
    "webs.appStore.board": "ZetaBoard",
    "webs.appStore.bookfresh": "Appointments",
    "webs.appStore.bookfreshbeta": "Appointments Beta",
    "webs.appStore.buzzworthy": "Buzzworthy",
    "webs.appStore.byline": "By: ",
    "webs.appStore.cafepress_shop": "CafePress Shop",
    "webs.appStore.calendar": "Calendar",
    "webs.appStore.calendar2": "Calendar",
    "webs.appStore.calendar3": "calendar3",
    "webs.appStore.calendarjlin": "Calendar",
    "webs.appStore.chuck_beta": "chuck_beta",
    "webs.appStore.chuck_dev": "chuck_dev",
    "webs.appStore.comments": "comments app",
    "webs.appStore.construction": "Under Construction",
    "webs.appStore.contactme": "ContactMe",
    "webs.appStore.contactme_dev": "ContactMeDev",
    "webs.appStore.contactsbeta": "Contacts",
    "webs.appStore.danielisabeast": "Daniel is a Beast",
    "webs.appStore.demo": "demo",
    "webs.appStore.demo_localini": "demo_localini",
    "webs.appStore.demomark": "Mark Demo",
    "webs.appStore.diyseo": "DIYSEO",
    "webs.appStore.diyseobeta": "DIYSEO",
    "webs.appStore.documents": "Documents",
    "webs.appStore.documents1_dev": "documents1_dev",
    "webs.appStore.documents2_dev": "documents2_dev",
    "webs.appStore.documents3_dev": "documents3_dev",
    "webs.appStore.documents_test": "documents_test",
    "webs.appStore.donations": "Donations",
    "webs.appStore.donations1_dev": "donations1_dev",
    "webs.appStore.donations2_dev": "donations2_dev",
    "webs.appStore.donations3_dev": "donations3_dev",
    "webs.appStore.donations_test": "donations_test",
    "webs.appStore.etsystore": "Etsy Store",
    "webs.appStore.etsystorejlin": "Etsy Store Test",
    "webs.appStore.faq": "FAQ",
    "webs.appStore.faq1_dev": "faq1_dev",
    "webs.appStore.faq2_dev": "faq2_dev",
    "webs.appStore.faq3_dev": "faq3_dev",
    "webs.appStore.faq_test": "faq_test",
    "webs.appStore.featuredApp": "Featured App",
    "webs.appStore.feeds": "Feeds",
    "webs.appStore.filterAll": "All Apps",
    "webs.appStore.filterInstalled": "Installed Apps",
    "webs.appStore.filterWebs": "Webs Apps",
    "webs.appStore.fontastic": "Fontastic",
    "webs.appStore.formslocal": "Forms (local)",
    "webs.appStore.forums": "Forums",
    "webs.appStore.forumsbeta": "forumsbeta",
    "webs.appStore.forumsdev": "notusedbutidrissaystoadditback",
    "webs.appStore.friends": "Friends",
    "webs.appStore.friendsbeta": "Friends Beta",
    "webs.appStore.friendslocal": "Friends Local",
    "webs.appStore.friendsprod": "Friends Prod",
    "webs.appStore.fs": "Online Scheduling",
    "webs.appStore.goldmail": "GoldMail",
    "webs.appStore.googlesearch": "googlesearch_live",
    "webs.appStore.googlesearch1_dev": "googlesearch1_dev",
    "webs.appStore.googlesearch2_dev": "googlesearch2_dev",
    "webs.appStore.googlesearch3_dev": "googlesearch3_dev",
    "webs.appStore.googlesearch_test": "googlesearch_test",
    "webs.appStore.guestbook": "Guestbook",
    "webs.appStore.guestbookbeta": "guestbookbeta",
    "webs.appStore.hotdevelopment": "HotPrints (Dev)",
    "webs.appStore.hotnightly": "HotPrints (hpnightly)",
    "webs.appStore.hotprints": "HotPrints",
    "webs.appStore.hotstaging": "HotPrints (Staging)",
    "webs.appStore.idris": "Idris's App",
    "webs.appStore.idristesting": "Idris Testing",
    "webs.appStore.info": "Info",
    "webs.appStore.infobeta": "Info Beta",
    "webs.appStore.infolocal": "Info Local",
    "webs.appStore.infoprod": "Info Prod",
    "webs.appStore.information": "Information",
    "webs.appStore.install": "Install app",
    "webs.appStore.justfortest": "Another Test",
    "webs.appStore.kampyle": "Kampyle Feedback Analysis",
    "webs.appStore.lifestream": "LifeStream",
    "webs.appStore.links": "Links",
    "webs.appStore.livefaceonweb_101": "Virtual Spokesperson",
    "webs.appStore.localini": "localini",
    "webs.appStore.location": "Location",
    "webs.appStore.locations1_dev": "locations1_dev",
    "webs.appStore.locations2_dev": "locations2_dev",
    "webs.appStore.locations3_dev": "locations3_dev",
    "webs.appStore.locations_test": "locations_test",
    "webs.appStore.login": "Login Page",
    "webs.appStore.logogizmo": "LogoGizmo",
    "webs.appStore.manage": "Manage This App",
    "webs.appStore.mavenfeed": "Maven Feed",
    "webs.appStore.meebo": "Meebo IM",
    "webs.appStore.member": "Website",
    "webs.appStore.memberbeta": "memberbeta app",
    "webs.appStore.members": "Members",
    "webs.appStore.membersbeta": "membersbeta",
    "webs.appStore.membersprod": "membersprod",
    "webs.appStore.mobile": "Mobile Website",
    "webs.appStore.online_scheduling": "Appointments",
    "webs.appStore.optimisation": "Plug in SEO",
    "webs.appStore.optimisation_dev": "Plugin SEO (dev)",
    "webs.appStore.optimisation_test": "Plugin SEO (test)",
    "webs.appStore.pagebuilder": "Page Builder",
    "webs.appStore.paytest": "Pay Test",
    "webs.appStore.photos": "Photo Albums",
    "webs.appStore.photos-mark": "Standalone Photos Test",
    "webs.appStore.photos-standalone": "Standalone Photos Test",
    "webs.appStore.photos2": "Photo Gallery Prod",
    "webs.appStore.photosarun": "Photo Gallery",
    "webs.appStore.photosbeta": "Photo Gallery",
    "webs.appStore.photosdom": "Photos Dom",
    "webs.appStore.photosjlin": "jlinphotos",
    "webs.appStore.photosprod": "Photos (PROD)",
    "webs.appStore.photosseon": "Photo Gallery",
    "webs.appStore.playground": "Platform Playground",
    "webs.appStore.podcast": "Music and Podcast",
    "webs.appStore.podcast1_dev": "podcast1_dev",
    "webs.appStore.podcast2_dev": "podcast2_dev",
    "webs.appStore.podcast3_dev": "podcast3_dev",
    "webs.appStore.podcast_test": "podcast_test",
    "webs.appStore.podcastpatrick": "Podcast",
    "webs.appStore.polldaddy": "PollDaddy",
    "webs.appStore.prayers": "Prayer Requests",
    "webs.appStore.prayers1": "Prayers 1",
    "webs.appStore.prayers2": "Prayers 2",
    "webs.appStore.prayers3": "Prayers 3",
    "webs.appStore.prayerstest": "Prayers Test",
    "webs.appStore.profile": "Profile",
    "webs.appStore.profilebeta": "Profile QA",
    "webs.appStore.profilebeta2": "Profile BetaPlatform",
    "webs.appStore.profilelocal": "Profile Local",
    "webs.appStore.profileprod": "Profile Prod",
    "webs.appStore.projectboard": "Work-from-Home Projects",
    "webs.appStore.promotions": "Promotions",
    "webs.appStore.railsqa": "railsqa",
    "webs.appStore.related": "Related Content",
    "webs.appStore.relatedcontent": "Related Content",
    "webs.appStore.richcontent": "Pluck Rich Content",
    "webs.appStore.root": "Root",
    "webs.appStore.rosterbeta": "rosterbeta app",
    "webs.appStore.sandboxjlin": "Your App Name Here",
    "webs.appStore.scrapbook": "scrapbook app",
    "webs.appStore.screenshots": "Screenshots",
    "webs.appStore.shawn_dev": "shawn_dev",
    "webs.appStore.socialPrompt": "To install this app, <a href=\"/sites/dashboard/settings\" target=\"_top\">turn social mode on<\/a>.",
    "webs.appStore.testimonials": "Testimonials",
    "webs.appStore.testimonials1_dev": "testimonials1_dev",
    "webs.appStore.testimonials2_dev": "testimonials2_dev",
    "webs.appStore.testimonials3_dev": "testimonials3_dev",
    "webs.appStore.testimonials_test": "testimonials_test",
    "webs.appStore.tos": "Terms of Service",
    "webs.appStore.trusthop": "All*Star Experts",
    "webs.appStore.typekit": "Typekit",
    "webs.appStore.uhaveaudio": "UHaveAudio (DEPRECATED)",
    "webs.appStore.uninstall": "Uninstall &ldquo;{name}&rdquo; and remove associated pages?",
    "webs.appStore.util": "Util",
    "webs.appStore.vblog": "Video Blog",
    "webs.appStore.vblogdev": "Video Blog",
    "webs.appStore.video": "Video",
    "webs.appStore.videos": "Videos",
    "webs.appStore.videos_new": "old videos dev",
    "webs.appStore.videosbeta": "videosbeta",
    "webs.appStore.videosdev": "videosdev",
    "webs.appStore.voicemail": "Voicemail",
    "webs.appStore.voicemaildev": "Voicemail Dev",
    "webs.appStore.webformsbeta": "Web Forms",
    "webs.appStore.webstore": "Web Store",
    "webs.appStore.webstorebeta": "webstorebeta",
    "webs.appStore.wibiya": "Wibiya Social Bar",
    "webs.appStore.wiki": "Wiki",
    "webs.appStore.wufoo": "Wufoo Forms",
    "webs.appStore.zeemaps": "Zeemaps",
    "webs.appStore.zeemaps_dev": "Zeemaps Dev"
});
