define({
    "webs.pages.ads.freeUserWithDomain.body": "Get unlimited pages, no Webs ads, plus email that matches your domain name.",
    "webs.pages.ads.freeUserWithDomain.title": "Look More Professional",
    "webs.pages.ads.freeUserWithoutDomain.subtitle": "Look More Professional",
    "webs.pages.ads.freeUserWithoutDomain.title": "Get a Custom Domain",
    "webs.pages.cannotDeleteHomepage": "You cannot delete your homepage.",
    "webs.pages.cannotDeleteLastPage": "You cannot delete your last page.",
    "webs.pages.cannotSetPageAsHomePage": "An external page cannot be set as the home page.",
    "webs.pages.controls.addpage": "Add Page",
    "webs.pages.controls.continue": "Continue",
    "webs.pages.controls.goback": "Go Back",
    "webs.pages.controls.pagename": "Page Name",
    "webs.pages.deleteAppDialog.deleteButton": "Delete",
    "webs.pages.deleteAppDialog.description": "Your users will not be able to find this page unless you link to it somewhere else in your site.",
    "webs.pages.deleteAppDialog.error.generic": "There was an error submitting your changes.",
    "webs.pages.deleteAppDialog.header": "Are you sure you want to delete this page from your navbar?",
    "webs.pages.dragHelptip": "<b>Tip:<\/b> Drag page handles <b>up & down<\/b> to reorder and <b>left & right<\/b> to create subpages.",
    "webs.pages.edit": "Edit This Page",
    "webs.pages.hide.error": "There was an error submitting your changes.",
    "webs.pages.hide.hide": "Hide",
    "webs.pages.hide.hidenavbar": "Hide from Navbar",
    "webs.pages.hide.notabletofind": "Your users will not be able to find this page unless you link to it somewhere else in your site.",
    "webs.pages.hide.rearrangenavbar": "This may rearrange your navbar.",
    "webs.pages.hide.removefromnavbar": "Are you sure you want to remove this page from your navbar?",
    "webs.pages.hide.show": "Show",
    "webs.pages.hide.showinnavbar": "Show this page in your navbar?",
    "webs.pages.hide.shownavbar": "Show in Navbar",
    "webs.pages.layouts.error.submission": "There was an error submitting your changes.",
    "webs.pages.layouts.headerLeftSidebar": "Banner Sidebar Left",
    "webs.pages.layouts.headerNoSidebar": "Banner",
    "webs.pages.layouts.headerRightSidebar": "Banner Sidebar Right",
    "webs.pages.layouts.headerSidebarLeft": "Banner Sidebar Left",
    "webs.pages.layouts.headerSidebarRight": "Banner Sidebar Right",
    "webs.pages.layouts.noHeaderLeftSidebar": "Sidebar Left",
    "webs.pages.layouts.noHeaderNoSidebar": "Standard",
    "webs.pages.layouts.noHeaderRightSidebar": "Sidebar Right",
    "webs.pages.layouts.noHeadernoSidebar": "Standard",
    "webs.pages.layouts.savelayout": "Save Layout",
    "webs.pages.layouts.title": "Select a layout for this page.",
    "webs.pages.notification.annualAutoRenewOff.enhanced": "Your Enhanced package expires soon. <a href=\"{url}&bundle.0.bundleSKU=ENHANCED_ONE_DAY_SALE\">Save 33% today<\/a> when you renew early.",
    "webs.pages.notification.annualAutoRenewOff.pro": "Your Pro package expires soon. <a href=\"{url}&bundle.0.bundleSKU=PRO_SALE_111610\">Save 60% today<\/a> when you renew early.",
    "webs.pages.notification.annualAutoRenewOff.starter": "Your Starter package expires soon. <a href=\"{url}&bundle.0.bundleSKU=STARTER_15PCT_OFF\">Save 15% today<\/a> when you renew early.",
    "webs.pages.notification.generic": "Generic Pane Notification",
    "webs.pages.pagelist.SavePageTitleHover": "Save Page Title",
    "webs.pages.pagelist.addpagebutton": "Add A New Page",
    "webs.pages.pagelist.andallcontents": "and all of its contents",
    "webs.pages.pagelist.appstoretitle": "App Store",
    "webs.pages.pagelist.clonelabel": "copy",
    "webs.pages.pagelist.delete": "Delete",
    "webs.pages.pagelist.deleteandallcontents": "Delete \"{section_name}\" and all of its contents",
    "webs.pages.pagelist.edit": "Edit This Page",
    "webs.pages.pagelist.hidden": "hidden",
    "webs.pages.pagelist.hiddensection": "In a hidden section.",
    "webs.pages.pagelist.hidefrom": "Hide From",
    "webs.pages.pagelist.hover.CloneLink": "Copy Link",
    "webs.pages.pagelist.hover.ClonePage": "Copy Page",
    "webs.pages.pagelist.hover.DeleteLink": "Delete Link",
    "webs.pages.pagelist.hover.DeletePage": "Delete Page",
    "webs.pages.pagelist.hover.MoveLink": "Move Link",
    "webs.pages.pagelist.hover.MovePage": "Move Page",
    "webs.pages.pagelist.hover.RenameLink": "Rename Link",
    "webs.pages.pagelist.hover.RenamePage": "Rename Page",
    "webs.pages.pagelist.hover.SaveLinkTitle": "Save Link Title",
    "webs.pages.pagelist.hover.SavePageTitle": "Save Page Title",
    "webs.pages.pagelist.metatag": "MetaTags",
    "webs.pages.pagelist.metatagdesc": "MetaTags/Description",
    "webs.pages.pagelist.navbar": "Navbar",
    "webs.pages.pagelist.no": "No",
    "webs.pages.pagelist.pageisprotected": "This page is protected.",
    "webs.pages.pagelist.pagesettings": "Page Settings",
    "webs.pages.pagelist.paneDoneButton": "Done",
    "webs.pages.pagelist.password.protect": "Password Protect",
    "webs.pages.pagelist.password.protection": "Password Protection",
    "webs.pages.pagelist.rename": "Rename",
    "webs.pages.pagelist.savepagetitle": "Save Page Title",
    "webs.pages.pagelist.settings": "Settings",
    "webs.pages.pagelist.showin": "Show In",
    "webs.pages.pagelist.title": "My Pages",
    "webs.pages.pagelist.updatemetatags": "Update MetaTags",
    "webs.pages.pagelist.updatetitletagdesc": "Update title/tags/description",
    "webs.pages.pagelist.yes": "Yes",
    "webs.pages.pagetype.about": "About",
    "webs.pages.pagetype.basePage": "Subclass This.",
    "webs.pages.pagetype.contact": "Contact",
    "webs.pages.pagetype.default": "Default",
    "webs.pages.pagetype.gallery": "Photo Gallery",
    "webs.pages.pagetype.services": "Services",
    "webs.pages.pagetype.testimonials": "Testimonials",
    "webs.pages.password.accesspermission": "Choose this page's access permissions.",
    "webs.pages.password.allow.allowonly": "Allow only",
    "webs.pages.password.allow.allowonlyorhigher": "Allow only {group} or higher permission level group to view this page.",
    "webs.pages.password.allow.anyone": "Allow anyone to view this page",
    "webs.pages.password.allow.members": "Allow only members of this website to view this page",
    "webs.pages.password.allow.orhigher": "or higher permission level group to view this page.",
    "webs.pages.password.allow.require": "Require visitors to enter a specified password to view this page",
    "webs.pages.password.everyone": "Everyone",
    "webs.pages.password.globalsetting": "This is a global setting. The same username and password will be used for all password protected pages.",
    "webs.pages.password.members": "Members",
    "webs.pages.password.password": "Password",
    "webs.pages.password.password.error": "Password cannot be blank or contain tabs",
    "webs.pages.password.premium": "Premium Feature",
    "webs.pages.password.savepermission": "Save Permissions",
    "webs.pages.password.username": "Username",
    "webs.pages.password.username.error": "Username cannot be blank or contain tabs",
    "webs.pages.rename": "Rename Page",
    "webs.pages.renameDialog.error.generic": "There was an error submitting your changes.",
    "webs.pages.renameDialog.error.invalidChars": "Page name contains invalid characters",
    "webs.pages.renameDialog.header": "Choose how this page's name will appear in your navbar.",
    "webs.pages.renameDialog.pageNameLabel": "Page Name",
    "webs.pages.renameDialog.remainingCharCount": "{chars} character left",
    "webs.pages.renameDialog.remainingCharCount.1": "{chars} character left",
    "webs.pages.renameDialog.remainingCharCount.other": "{chars} characters left",
    "webs.pages.renameDialog.saveChanges": "Save Changes",
    "webs.pages.revertDialog.description": "Your page will be set back to the previously published version.",
    "webs.pages.revertDialog.error.generic": "There was an error submitting your changes.",
    "webs.pages.revertDialog.header": "Are you sure you want to revert your changes?",
    "webs.pages.revertDialog.noButton": "Cancel",
    "webs.pages.revertDialog.yesButton": "Yes!"
});
