define({
    "webs.websid.accountSettings": "Account Settings",
    "webs.websid.addSite": "Add a New Site",
    "webs.websid.cancel": "Cancel",
    "webs.websid.delete.confirmation": "You really want to delete your account?",
    "webs.websid.deleteAccount": "Delete Account",
    "webs.websid.email.change.confirm": "A confirmation email has been sent to the new email address. Please follow the link included in that email.",
    "webs.websid.enterPasswordToDelete": "Enter your password to delete.",
    "webs.websid.loadingSites": "Loading Your Sites...",
    "webs.websid.logout": "Logout",
    "webs.websid.passwordChanged": "Password Changed!",
    "webs.websid.somethingNotLiked": "Was there something you didn't like?",
    "webs.websid.tellUs": "Tell us your problem",
    "webs.websid.unsubscribe.confirmation": "Are you sure? This will remove you from this site and its mailing list. This will also delete your profile on this site.",
    "webs.websid.unsubscribed": "You have unsubscribed from",
    "webs.websid.viewAllSites": "View All Sites",
    "webs.websid.website.delete": "Delete Website",
    "webs.websid.website.deleted": "has been deleted",
    "webs.websid.website.unsubscribe": "Unsubscribe"
});
