define({
    "webs.error.confirmPassword": "Please confirm your password by typing it in both fields.",
    "webs.error.currentPassword.mismatch": "Your current password is incorrect.",
    "webs.error.dashboard.badSite": "This site does not exist.",
    "webs.error.dashboard.cannotDeleteDomainOnlySite": "Cannot delete a Domain only account",
    "webs.error.dashboard.cannotDeletePremiumSite": "Premium websites cannot be deleted.",
    "webs.error.dashboard.wrongPassword": "Incorrect password entered.",
    "webs.error.email.invalid": "Please enter a valid email address.",
    "webs.error.exception.generic": "The operation encountered an error.",
    "webs.error.fillAllFields": "Please fill out all fields.",
    "webs.error.generic": "There was an error.",
    "webs.error.internalServer.encounteredTempGlitch": "Oops, we have encountered a temporary glitch.",
    "webs.error.internalServer.pleaseGoBackAndTryAgain": "&larr;&nbsp;&nbsp;Please go back and try again",
    "webs.error.internalServer.problemPersistsTryCheckingBack": "If this problem persists, try checking back in 10-15 minutes.",
    "webs.error.internalServer.shouldResolvedMomentarily": "Sorry for the trouble, this should be resolved momentarily",
    "webs.error.internalServer.title.access_error": "Access Error",
    "webs.error.internalServer.title.whoops": "Whoops!",
    "webs.error.internalServer.webs": "Webs",
    "webs.error.invalid.password": "Your password is incorrect.",
    "webs.error.member.email.duplicate": "The supplied email is already a registered WebsID. You must choose an email address that is not already a WebsID.",
    "webs.error.timeout": "The operation timed out.",
    "webs.error.tryAgain": "Sorry, it seems like we have encountered a temporary glitch.  Please refresh the page to try again."
});
