jQuery191047765525500290096_1417752821020({
    "GetLanguagesResult": [{
        "LanguageCode": "AKA",
        "Name": "Akan"
    }, {
        "LanguageCode": "ARA",
        "Name": "Arabic"
    }, {
        "LanguageCode": "CAN",
        "Name": "Cantonese"
    }, {
        "LanguageCode": "CHI",
        "Name": "Chinese"
    }, {
        "LanguageCode": "DUT",
        "Name": "Dutch"
    }, {
        "LanguageCode": "ETH",
        "Name": "Ethiopian"
    }, {
        "LanguageCode": "FAR",
        "Name": "Farsi (Persian)"
    }, {
        "LanguageCode": "FIL",
        "Name": "Filipino"
    }, {
        "LanguageCode": "FRE",
        "Name": "French"
    }, {
        "LanguageCode": "GER",
        "Name": "German"
    }, {
        "LanguageCode": "GRE",
        "Name": "Greek"
    }, {
        "LanguageCode": "GUJ",
        "Name": "Gujarati"
    }, {
        "LanguageCode": "HEB",
        "Name": "Hebrew"
    }, {
        "LanguageCode": "HIN",
        "Name": "Hindi"
    }, {
        "LanguageCode": "IND",
        "Name": "Indian"
    }, {
        "LanguageCode": "ITA",
        "Name": "Italian"
    }, {
        "LanguageCode": "JAP",
        "Name": "Japanese"
    }, {
        "LanguageCode": "KAN",
        "Name": "Kannada"
    }, {
        "LanguageCode": "KON",
        "Name": "Konkani"
    }, {
        "LanguageCode": "KOR",
        "Name": "Korean"
    }, {
        "LanguageCode": "LAO",
        "Name": "Laotian"
    }, {
        "LanguageCode": "LIT",
        "Name": "Lithuanian"
    }, {
        "LanguageCode": "MAY",
        "Name": "Malayalam"
    }, {
        "LanguageCode": "MAN",
        "Name": "Mandarin"
    }, {
        "LanguageCode": "MAR",
        "Name": "Marathi"
    }, {
        "LanguageCode": "PAK",
        "Name": "Pakastani"
    }, {
        "LanguageCode": "PER",
        "Name": "Persian"
    }, {
        "LanguageCode": "POL",
        "Name": "Polish"
    }, {
        "LanguageCode": "POR",
        "Name": "Portuguese"
    }, {
        "LanguageCode": "PUN",
        "Name": "Punjabi"
    }, {
        "LanguageCode": "ROM",
        "Name": "Romanian"
    }, {
        "LanguageCode": "RUS",
        "Name": "Russian"
    }, {
        "LanguageCode": "SER",
        "Name": "Serbo-Croatia"
    }, {
        "LanguageCode": "SIG",
        "Name": "Sign Language"
    }, {
        "LanguageCode": "SPA",
        "Name": "Spanish"
    }, {
        "LanguageCode": "SWE",
        "Name": "Swedish"
    }, {
        "LanguageCode": "TAG",
        "Name": "Tagalog (Filipino)"
    }, {
        "LanguageCode": "TAI",
        "Name": "Taiwanese"
    }, {
        "LanguageCode": "TAM",
        "Name": "Tamil"
    }, {
        "LanguageCode": "TEL",
        "Name": "Telugu"
    }, {
        "LanguageCode": "TIG",
        "Name": "Tigrigra"
    }, {
        "LanguageCode": "TUL",
        "Name": "Tulu"
    }, {
        "LanguageCode": "TUR",
        "Name": "Turkish"
    }, {
        "LanguageCode": "UKR",
        "Name": "Ukrainian"
    }, {
        "LanguageCode": "URD",
        "Name": "Urdu"
    }, {
        "LanguageCode": "VIE",
        "Name": "Vietnamese"
    }, {
        "LanguageCode": "YOR",
        "Name": "Yoruba"
    }
    ]
});
