var getuser = {
    "status": 0,
    "statusInfo": {
        "global": ""
    },
    "data": {
        "id": 1274469185,
        "idstr": "1274469185",
        "class": 1,
        "screen_name": "扬帆计划",
        "name": "扬帆计划",
        "province": "11",
        "city": "1000",
        "location": "北京",
        "description": "【扬帆计划】通过捐助课外图书、举行扬帆夏令营、开办生态教育移民扬帆班、援助优秀教师等活动，帮助偏远贫困地区的孩子改善现状、实现梦想。2014年9月1日，正式推出国内首款自助捐助APP【扬帆公益助手】 ，打造互联网公益新领域。",
        "url": "http://blog.sina.com.cn/yangfanjihua",
        "profile_image_url": "http://tp2.sinaimg.cn/1274469185/50/5712456895/0",
        "cover_image": "http://ww2.sinaimg.cn/crop.0.0.920.300/4bf6db41jw1elm8lv1143j20pk08cjsu.jpg",
        "profile_url": "yangfanjihua",
        "domain": "yangfanjihua",
        "weihao": "",
        "gender": "f",
        "followers_count": 212514,
        "friends_count": 703,
        "pagefriends_count": 5,
        "statuses_count": 8105,
        "favourites_count": 8,
        "created_at": "Fri Aug 28 16:14:11 +0800 2009",
        "following": false,
        "allow_all_act_msg": false,
        "geo_enabled": true,
        "verified": true,
        "verified_type": 7,
        "remark": "",
        "status": {
            "created_at": "Thu Dec 04 11:26:31 +0800 2014",
            "id": 3784017725582238,
            "mid": "3784017725582238",
            "idstr": "3784017725582238",
            "text": "#扬帆书评志愿者招募#来自扬帆志愿者@一画家居 的《影响孩子一生的世界名著：骑鹅旅行记》http://t.cn/RzajjIv的书评：1906至1907年，《骑鹅旅行记》被瑞典作为历史、地理教科书出版。这部童话巨著使作者拉格洛夫成为蜚声世界的文豪，赢得了...关注@扬帆计划 我们一起来圆山区孩子的读书梦  ",
            "source_type": 1,
            "source": "<a href=\"http://app.weibo.com/t/feed/3SC7Bg\" rel=\"nofollow\">金果微博推</a>",
            "favorited": false,
            "truncated": false,
            "in_reply_to_status_id": "",
            "in_reply_to_user_id": "",
            "in_reply_to_screen_name": "",
            "pic_ids": ["4bf6db41jw1emxhjl5aqaj20c814ftf1"],
            "thumbnail_pic": "http://ww4.sinaimg.cn/thumbnail/4bf6db41jw1emxhjl5aqaj20c814ftf1.jpg",
            "bmiddle_pic": "http://ww4.sinaimg.cn/bmiddle/4bf6db41jw1emxhjl5aqaj20c814ftf1.jpg",
            "original_pic": "http://ww4.sinaimg.cn/large/4bf6db41jw1emxhjl5aqaj20c814ftf1.jpg",
            "geo": null,
            "reposts_count": 0,
            "comments_count": 0,
            "attitudes_count": 0,
            "mlevel": 0,
            "visible": {
                "type": 0,
                "list_id": 0
            },
            "darwin_tags": []
        },
        "ptype": 0,
        "allow_all_comment": true,
        "avatar_large": "http://tp2.sinaimg.cn/1274469185/180/5712456895/0",
        "avatar_hd": "http://ww3.sinaimg.cn/crop.0.0.179.179.1024/4bf6db41jw1emv5qaqmsvj2050050glm.jpg",
        "verified_reason": "中华思源工程扶贫基金会的重要公益助学项目",
        "verified_trade": "",
        "verified_reason_url": "",
        "verified_source": "",
        "verified_source_url": "",
        "verified_state": 0,
        "verified_level": 3,
        "verified_reason_modified": "",
        "verified_contact_name": "扬帆计划",
        "verified_contact_email": "yangfanjihua@sina.com",
        "verified_contact_mobile": "010-58983282",
        "follow_me": false,
        "online_status": 1,
        "bi_followers_count": 579,
        "lang": "zh-cn",
        "star": 0,
        "mbtype": 0,
        "mbrank": 0,
        "block_word": 0,
        "block_app": 0,
        "credit_score": 80,
        "urank": 0
    }
};

